### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by aldendaniels** [erikras/redux-form-material-ui#10]
Changes are not being processed. Maybe this is due to breaking changes in the new rc?

Alden

**Comment by erikras** [comment]
Yes, thanks. Known bug. Working on it.

**Comment by erikras** [comment]
Fixed in [`v3.0.0`](https://github.com/erikras/redux-form-material-ui/releases/tag/v3.0.0).

**Comment by aldendaniels** [comment]
@erikras - 👍 Thanks for the quick turnaround!
