### ISSUE TITLE
Can't use functional components with ref

### ISSUE THREAD

**Issue by liviuignat** [erikras/redux-form-material-ui#100]
Can't use functional components, because they don't support ref, eg:
```js
export const SomeForm = ({
  handleSubmit = () => {},
  isLoading = false,
  errorMessage = '',
}) => (
  <form onSubmit={handleSubmit}>
    <Field
      component={TextField}
      withRef
      ref="password"
      fullWidth
      disabled={isLoading}
      name="password"
      type="password"
      hintText={'E-Mail'}
      validate={[required, email]}
    />

    {errorMessage && <ErrorMessage>{errorMessage}</ErrorMessage>}
  </form>
);
```

Any ideas?

**Comment by mihirsoni** [comment]
React doesn't allow ref inside functional component more details [here](https://facebook.github.io/react/docs/refs-and-the-dom.html#refs-and-functional-components)


**You may not use the ref attribute on functional components** because they don't have instances:
