### ISSUE TITLE
<TextField type="date" /> behaves strangely with change event

### ISSUE THREAD

**Issue by durre** [erikras/redux-form-material-ui#104]
Let's say I wish to input the date '2016-12-31' in the following field.

```
import { Field } from 'redux-form'
import { TextField } from 'redux-form-material-ui'

<Field 
  name="startDate" 
  component={TextField} 
  type="date" 
  max="3000-12-31" 
  floatingLabelText="Start date" 
  floatingLabelFixed 
/>
```

The resulting date is actually '2016-12-01'. Redux fires two change events:
`{ type: '@@redux-form/CHANGE', payload: '2016-12-03' }`
`{ type: '@@redux-form/CHANGE', payload: '2016-12-01' }`

I haven't been able to figure out why. I can however fix the issue by doing this:

```
<Field 
  name="startDate" 
  component={TextField} 
  type="date" 
  max="3000-12-31" 
  onChange={() => {}} <-- fixes the problem
  floatingLabelText="Start date" 
  floatingLabelFixed 
/>
```

"redux-form-material-ui": "4.1.2"
"material-ui": "0.17.0"

**Comment by mihirsoni** [comment]
Tried with latest version, not able to reproduce it. Let me know if still this is an issue.
