### ISSUE TITLE
defaultDate property is not working in DatePicker 

### ISSUE THREAD

**Issue by xfo** [erikras/redux-form-material-ui#105]
defaultDate property is not working in DatePicker

**Comment by erback** [comment]
@xfo set it via the initialValues field, like so:

```
initialValues:{
   NAME_OF_YOUR_FIELD: new Date()
  }
```

**Comment by mihirsoni** [comment]
We don't support defaultValues. 

>Because of the strict "controlled component" nature of redux-form, some of the Material UI functionality related to defaulting of values has been disabled e.g. defaultValue, defaultDate, defaultTime, defaultToggled, defaultChecked, etc. If you need a field to be initialized to a certain state, you should use the initialValues API of redux-form.

**Comment by swapnil-srivastava** [comment]
is this supported now ? using `initialize()` from redux-form and set `defaultDate` on the date picker component

```
  useEffect(() => {
    // api call ====> 
    initialize({
      NAME_OF_YOUR_FIELD: new Date('December 17, 1995 03:24:00'),
    });
    return () => {
      // cleanup
    };
  }, []);
```

can we reopen this bug
