### ISSUE TITLE
Set TextField value from props

### ISSUE THREAD

**Issue by sun2rise** [erikras/redux-form-material-ui#106]
Hi,
i am trying to set the TextField value from a property of this.props without using the ref, is it possible?

I am trying with
```js
<Field
  name="fieldOne"
  value={this.props.myvalue} // <- not working
  type="number"
  component={TextField}
/>
```

**Comment by programisti** [comment]
Did you tried `defaultValue={this.props.myvalue}` ?

**Comment by sun2rise** [comment]
Yes it works now because it was fixed: https://github.com/erikras/redux-form-material-ui/commit/89f37320ce88d2b1ee0774a613afd920dc39fa61

Thanks a lot!
