### ISSUE TITLE
setting value of component

### ISSUE THREAD

**Issue by oallouch** [erikras/redux-form-material-ui#11]
Hi,
I must be doing something wrong, but when I pass a value to a Field, this value doesn't get passed to the wrapped SelectField component.

Thx in advance,

Olivier Allouch
www.illicotravel.com

**Comment by erikras** [comment]
Try again with [`v3.0.0`](https://github.com/erikras/redux-form-material-ui/releases/tag/v3.0.0). There was a bug involving the breaking change from redux-form v6rc2.

**Comment by tzapu** [comment]
with 4.0.1 and a checkbox i seem to have the same issue, can t check by default a checkbox

i tried
`<Field name="platformWeb" component={Checkbox} label="Web SDK" value={true} />`
but must be doing something wrong.

thank you for a wonderful package.

**Comment by vysakh0** [comment]
@tzapu  `value={true}` shouldn't it be `checked={true}` ?

**Comment by tzapu** [comment]
neither worked. i thik it reads value and sets internally checked... at least that s what i understood from the source
