### ISSUE TITLE
Tabbing through select fields can causes value to change without user input on Blur event

### ISSUE THREAD

**Issue by dangerdespain** [erikras/redux-form-material-ui#110]
Encountered behavior: While tabbing through form fields, tabbing through select fields changes the value to null or to other items in the select field. This does not seem to be a behavior with just a regular material-ui form.

Expected: Tabbing through the fields should take me to the next field without modifying the form value.

![error_on_blur](https://cloud.githubusercontent.com/assets/6187137/23637021/6c5ac1fa-0296-11e7-8e0c-fcbf60ddd55e.gif)

![screen shot 2017-03-06 at 5 56 23 pm](https://cloud.githubusercontent.com/assets/6187137/23637023/6f55e20e-0296-11e7-9148-6117b0a4e490.png)

Just wanted to drop a note of thanks for this library! It's been fantastic glue between redux-form and mui.

**Comment by Guibod** [comment]
Same as https://github.com/erikras/redux-form-material-ui/issues/94
That's fixed in a PR that is already merged ( #95 ) , but we are waiting for 4.1.3 release ( #111 )

**Comment by dangerdespain** [comment]
Thanks! My apologies for not seeing the previous issue. Looking forward to the next release (:
