### ISSUE TITLE
How to install pre-release ? or do you plan to release 4.1.3 ?

### ISSUE THREAD

**Issue by Guibod** [erikras/redux-form-material-ui#111]
Hi there, last fixes (onBlur support for SelectField) is a requirement for my production setup. Unfortunately, there is no release planned for 4.1.3 yet, and i'm in a dire need of a fix.
I tried to install `redux-form-material-ui` from github, but that's not possible as it relies on the `dist` and `lib` directories only added by the CI. I end with an empty directory.

How can I achieve a pre-release install of this package ?
Alternatively, when does the 4.1.3 release is planned ?

Thanks Erik for the amazing work on redux-form.

**Comment by giacomocariello** [comment]
+1 on 4.1.3 release :-)

**Comment by Guibod** [comment]
@erikras could you please do something about that ?

**Comment by nmaves** [comment]
We really need to push for the next release.  Can any of the contributors please push a new release to npm?

**Comment by Guibod** [comment]
I git cloned the repository in my project lib and removed dependency from my package.json for the time being.

**Comment by nmaves** [comment]
That is really a failure of the development community.  There is no reason not to cut a micro release for these fixes.

**Comment by erikras** [comment]
[`v4.1.3`](https://github.com/erikras/redux-form-material-ui/releases/tag/v4.1.3) released.
