### ISSUE TITLE
Prop 'error' of Slider is deprecated

### ISSUE THREAD

**Issue by Bonitis** [erikras/redux-form-material-ui#112]
I recently added a slider to one of my forms that uses field level validation. I got this console error:
<img width="858" alt="screen shot 2017-03-11 at 10 44 53 am" src="https://cloud.githubusercontent.com/assets/15722894/23825494/fb004808-0647-11e7-861d-651cf48a1990.png">

Here is my slider component:
``` javascript
<Field
      component={Slider}
      format={null}
      name="lowLimit"
      defaultValue={60}
      step={5}
      min={0}
      max={100}
      sliderStyle={styles.sliderStyle}
      validate={[required, effortRange, lowerThanHighLimit]}
/>
```

Is there a better way to do validation on a Slider component, or is there an update coming to address this error?

**Comment by mihirsoni** [comment]
This shouldn't be with new version.
