### ISSUE TITLE
React warning on TextField

### ISSUE THREAD

**Issue by advance512** [erikras/redux-form-material-ui#113]
> Warning: TextField contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components

react@15.4.2
material-ui@0.17.0
redux-form@6.5.0
redux-form-material-ui@4.1.2

**Comment by jburk-foliage** [comment]
I'm still seeing this with 4.1.3.

**Comment by nmaves** [comment]
Can you post your code here?

**Comment by jburk-foliage** [comment]
Hmm... I was setting `defaultValue={null}`. Removing this fixed the warning. I assume there was a good reason I had that in there, but it doesn't seem to be necessary now.

Not sure if @advance512 is still seeing this warning - perhaps this issue can be closed.

**Comment by erikras** [comment]
You need to remove the `defaultValue={null}`.

#60

**Comment by k96white** [comment]
Is there any solution for this, I wanted both of them
