### ISSUE TITLE
Async Validation on components

### ISSUE THREAD

**Issue by godheaper** [erikras/redux-form-material-ui#117]
Is there a way to do asynchronous validation on the redux-form-material-ui?
I tried to link it with redux-form@6.5.0, but it seems that the async function does not return the error to the components in redux-form-material-ui.

```javascript
const asyncValidate = (values, dispatch) => {
  var emailValid = 0;
  return sleep(1000) // simulate server latency
    .then(() => {
      request.post(apiUrl + '/checkemail')
      .send(querystring.stringify({
        email: values.email,
      }))
      .end(function(err, result) {
        // const json = result.body;
        if (!err) {
          // console.log(props);
          var resValid = JSON.parse(JSON.parse(result.text).text).result;
          // It returns 1 if the email is found
          emailValid = resValid;
        }
      });
      setTimeout(() => {
        console.log(emailValid);
        if (emailValid === 1) {
          throw { email: 'Email is already taken !!!' };
        } else if (emailValid === 0) {
          dispatch(postRegister(values));
          resolve();
        }
      }, 500);
    })
}
```
![image](https://cloud.githubusercontent.com/assets/5469272/24139820/38158b12-0e50-11e7-8960-13ef99fbc924.png)

It just returns as an invalid Object, and is not read by redux-form as an Error object.
Can anyone help me with this? Is there a better way to do this in conjuction with using redux-form-material-ui?

**Comment by erikras** [comment]
Here's a working demo.

https://codesandbox.io/s/0RWElKV5G

**Comment by godheaper** [comment]
I've solved my own problem.

And I would like to share it here. The problem what I've experienced is, if you are validating through API (using like: Request, SuperAgent, and axios), you cannot put it inside the sleep Promise like in the example. The example does not show how to use a request HTTP client to access API. Before, I was using request and superagent to pass the error data to the asyncValidation. I realized that those do not support Promise (at least not out of the box like axios). So, I tried to use axios, and it looks like this...

`import axios from 'axios';
import request from 'superagent';
import querystring from 'querystring';
import path from 'path';
import srequest from 'sync-request';
import { postRegister } from '../actions/index';

const apiUrl = apiconfig.api_url_reducer;

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

const asyncValidate = (values , dispatch) => {
  var error = {};
  axios.post(apiUrl+'/checkemail', querystring.stringify({ email: values.email }))
  .then(function(response) {
    var resvalid = JSON.parse(response.data.text).result;
    if(resvalid === 1) {
      error.email = 'Email has been used...';
    }
  });

  return sleep(500).then(() => {
    if(error.email) {
      console.log(error);
      throw error;
    }
  });
};

export default asyncValidate;`

In my code, I've put the axios code outside the sleep Promise. Becuase it will not return a valid Promise if I put it inside.

Please provide examples for using API call for future references. Thank you.
