### ISSUE TITLE
DefaultValue not being set on TextField

### ISSUE THREAD

**Issue by sogoiii** [erikras/redux-form-material-ui#118]
If you define a defaultValue for a text field, it does not get shown.

Expected:
Set defaultValue=5, and have component render 5

Current:
Set defaultValue=5, and the component renders empty

example:
```javascript
<Field name='myInput'
   type='number'
   defaultValue='4'
   component={TextField}
   floatingLabelText='Please Enter A value'
 />
```

**Comment by erikras** [comment]
Fix published in [`v4.1.3`](https://github.com/erikras/redux-form-material-ui/releases/tag/v4.1.3).

**Comment by eranhirs** [comment]
Copy pasting the same example @sogoiii has provided, the component renders empty when using `v5.0.0-beta-2`

**Comment by emiliowl** [comment]
Same problem here with version v6.5.0.

**Comment by NguyenTheSon** [comment]
Same problem here with version v7.4.2
