### ISSUE TITLE
how to do input masking ?

### ISSUE THREAD

**Issue by EssamTarik** [erikras/redux-form-material-ui#120]

**Comment by kozze89** [comment]
Check out normalizing in redux-form: http://redux-form.com/6.6.0/examples/normalizing/

**Comment by erikras** [comment]
That @kozze89 said.

**Comment by renato-bohler** [comment]
Just for the record, if there's anyone out there wanting to create input masks using redux-form, I've made a library specifically to solve this problem.

Take a look at [`redux-form-input-masks`](https://github.com/renato-bohler/redux-form-input-masks) ([API documentation here](https://renato-bohler.github.io/redux-form-input-masks/#/)).
