### ISSUE TITLE
DatePicker does not appear to have a minDate prop

### ISSUE THREAD

**Issue by nicolechung** [erikras/redux-form-material-ui#123]
```
<Field
        name={props.date}
        className={form.datePickerDigit}
        component={DatePicker}
        minDate={props.todaysDate}
        label='Good until date'/>
```

I am using the above code but it appears that `minDate` does not appear as a props setting in the DatePicker.

![datepicker](https://cloud.githubusercontent.com/assets/771170/24476657/2da2b24c-14a2-11e7-9bc6-ac3beacabde0.gif)

**Comment by nicolechung** [comment]
Actually wait, I needed default date instead of minDate, and it turned out that because of the way redux-form works, I have to set that in the initial state **instead** of the default state.

Is there anywhere I can add this to the docs so other people don't ask, is that a thing?

**Comment by erikras** [comment]
You figured it out perfectly. 👍  More docs added in [`v4.2.0`](https://github.com/erikras/redux-form-material-ui/releases/tag/v4.2.0).
