### ISSUE TITLE
TextField defaultValue resetting when hitting zero characters

### ISSUE THREAD

**Issue by jmenglis** [erikras/redux-form-material-ui#127]
Dispatch is called on each keystroke, correct?  Wouldn't this cause a re-render of the component and when you hit zero characters or `value = ''` wouldn't the field then be set back to `defaultValue`.  I am referring to this PR #119.

**Comment by erikras** [comment]
Fix published in [`v4.2.0`](https://github.com/erikras/redux-form-material-ui/releases/tag/v4.2.0).
