### ISSUE TITLE
Issue with withRef and ref

### ISSUE THREAD

**Issue by AvadootNachankar** [erikras/redux-form-material-ui#13]
`
  import React, { Component, PropTypes } from 'react';
  import { connect } from 'react-redux';

  import { reduxForm, Field } from 'redux-form';
  import MenuItem from 'material-ui/MenuItem';
  import { RadioButton } from 'material-ui/RadioButton';
  import {
    Checkbox,
    RadioButtonGroup,
    SelectField,
    TextField,
    Toggle
  } from 'redux-form-material-ui';

  // Local import(s)
  import { getData, updateData } from '../actions';

  export const fields = ['first_name']

  const validate = values => {
    const errors = {}
    const requiredFields = [ 'first_name' ]
    requiredFields.forEach(field => {
      if (!values[ field ]) {
        errors[ field ] = 'Required'
      }
    })
    return errors
  }

  class UserEditForm extends Component {
    componentWillMount() {
      console.log("this.refs : ", this.refs);  // this.refs: {}
      this.refs.firstName.getRenderedComponent().getRenderedComponent().focus()  // on TextField

      // dispatching action: get Partner-Lead details
      this.props.getData(this.props.user_id);
    }

    onSubmit(formData) {
      this.props.updateData(this.props.user_id, formData);
    }

    render() {
      const { 
        fields: {first_name}, 
        pristine,
        handleSubmit, 
        submitting 
      } = this.props

      return (
        <form onSubmit={ handleSubmit(this.onSubmit.bind(this)) }>
          <Field name="first_name" component={TextField} hintText="First Name" floatingLabelText="First Name" ref="firstName" withRef {...first_name}/>
          <div>
            <button type="submit" disabled={pristine || submitting}>Submit</button>
          </div>
        </form>
      )
    }
  }

  export default reduxForm ({
      form: 'UserEditForm',
      fields,
      validate
    }, function mapStateToProps(state) {
      return {
        initialValues: state.userNode.getResponse,
      }
    }, {
      getData, updateData
  })(UserEditForm);
`

* I'm getting following error:
**UserEditForm.js:38 Uncaught TypeError: Cannot read property 'getRenderedComponent' of undefined**

* Please suggest what is the issue here.

**Comment by m2mathew** [comment]
@AvadootNachankar Can you fix the formatting to make it easier to read?

Try putting the `.focus()` into the `componentDidMount` method. Maybe that will cause it to focus _after_ the component has been rendered.

**Comment by m2mathew** [comment]
@AvadootNachankar Try putting the `.focus()` in a `componentDidMount` method. You have it in `componentWillMount`. I think it is trying to focus on something that has not rendered yet.

**Comment by erikras** [comment]
Yes, @m2mathew's answer is probably your solution.

**Comment by anthonybrown** [comment]
That answer is partially correct. I'm getting the same error but can't seem to find where it's coming from. I updated redux-form and now the form isn't working correctly

**Comment by anthonybrown** [comment]
[Here](https://gist.github.com/anthonybrown/e3e5b15a33646a0223e506d79edabb48) are the files. I have a `index.js` and a `register.js` file in components/auth/ directory.

**Comment by lileilei** [comment]
Uncaught TypeError: Cannot read property 'focus' of undefined
