### ISSUE TITLE
SelectField multiple POST issues

### ISSUE THREAD

**Issue by kelexel** [erikras/redux-form-material-ui#138]
Hello

I am having a bit of a headache, while using SelectField and multiple attributes together.

I am not sure if this is a real react-form-material-ui issue, or... not.

All I can say is when selecting multiple items, my form's field state is properly updated onchange, but when posting the data, all the selected values appear with the same key in the POST, rather than as an array.

Looking at my console, a typical post for a multiple SelectField (named f_168dc0014035f2c285ce805dd694db31)  looks like this:

```
f_168dc0014035f2c285ce805dd694db31:2d7e7dd2e8fba0f8629777b95d9eb34b
f_168dc0014035f2c285ce805dd694db31:577554427a55a29b066bf38932b098e2
f_168dc0014035f2c285ce805dd694db31:fc8ee92e6ece6860616fe6a24aa444d7
```

How may I make it look like this:

```
f_168dc0014035f2c285ce805dd694db31[]:2d7e7dd2e8fba0f8629777b95d9eb34b
f_168dc0014035f2c285ce805dd694db31[]:577554427a55a29b066bf38932b098e2
f_168dc0014035f2c285ce805dd694db31[]:fc8ee92e6ece6860616fe6a24aa444d7
```

The thing is, I would think adding `name={row.get('id')+'[]'}` would do the trick, but instead, it breaks everything :)

?

Here is how I invoke SelectField in the context of the app, ... It assumes you've just iterated thru form rows, and for each row (field), if the row type is "Select", return:

  ```
          <Field name={row.get('id')}
              component={SelectField}
              floatingLabelText={this.getLabel(row.get('label'), row.get('required'))}
              hintText={row.get('placeholder')}
              validate={this._getValidators(row.get('validators'))}
              value={row.get('value')}
              multiple={row.get('multiple')}
              autoWidth={true}
              className="select"
              >
              {row.get('options').map((label, idx) =>
                <MenuItem key={idx} value={idx} primaryText={label} />,
              ).toArray()}
            </Field>
```

Best regards

r.

**Comment by erikras** [comment]
You should not be setting the value. The value should be coming from `redux-form`.

**Comment by kelexel** [comment]
Edit, nevermind, my bad !!!

Issue is on my side, when I fetch the values out of the state, they are properly formatted.
It's when I pass them to fetch, to build the query string!!

Please forgive this ticket ;)
