### ISSUE TITLE
Use of RadioButtonGroup causes warning

### ISSUE THREAD

**Issue by jsinai** [erikras/redux-form-material-ui#139]
when I use a RadioButtonGroup like this, I get the warning below. Maybe it's something I'm doing wrong?

```javascript

<form>
  <Field component={RadioButtonGroup} name='testProp'
    defaultSelected={false} style={{'margin':'20px','textAlign':'left'}}>
    <RadioButton value='true' label='test 1' />
    <RadioButton value='false' label='test 2' />
  </Field>
</form>

```
warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check your code at App.js:27.

I have attached my project.

[test-radio.zip](https://github.com/erikras/redux-form-material-ui/files/922906/test-radio.zip)

**Comment by denis-andrikevich** [comment]
+1

**Comment by mihirsoni** [comment]
From looking at your attached project you're importing ```RadioButton``` from ```redux-form-material-ui``` which is not correct.

You should import ```RadioButton``` from ```material-ui```

```js
import { RadioButton } from 'material-ui/RadioButton'
```

Please look at provided examples 

https://github.com/erikras/redux-form-material-ui/blob/4336ce2cec402d84e37bbd763b0f8009d721144d/example/src/Form.js#L4
