### ISSUE TITLE
defaultDate not work for DatePicker

### ISSUE THREAD

**Issue by perevezencev** [erikras/redux-form-material-ui#144]
```
<Field
  name="eventDate"
  defaultDate={new Date(2010, 1, 1)}
  component={DatePicker}
  format={null}
   hintText="What day is the event?"
 />
```
![image](https://cloud.githubusercontent.com/assets/5954104/25557545/73366e38-2d1c-11e7-8d4d-4deab660db63.png)

**Comment by DillonF** [comment]
From the readme:

> Because of the strict "controlled component" nature of redux-form, some of the Material UI functionality related to defaulting of values has been disabled e.g. defaultValue, defaultDate, defaultTime, defaultToggled, defaultChecked, etc. If you need a field to be initialized to a certain state, you should use the initialValues API of redux-form.
