### ISSUE TITLE
Datepicker can't display error/required messages

### ISSUE THREAD

**Issue by timothyallan** [erikras/redux-form-material-ui#15]
The majority of the components are able to display error/required messages via the ```import mapError from './map'``` statement, except for poor old DatePicker. It's never able to display an error message as the props are never mapped.

**Comment by erikras** [comment]
This is true. There is no mention of `errorText` in the `DatePicker` docs, so I did not implement it, but it does, in fact, work. This will be fixed in the next version.

**Comment by erikras** [comment]
Fixed in [`v4.0.0`](https://github.com/erikras/redux-form-material-ui/releases/tag/v4.0.0).
