### ISSUE TITLE
How to access props in initialValues of redux form

### ISSUE THREAD

**Issue by vaibhav-systango** [erikras/redux-form-material-ui#151]
@erikras @hluedeke @sigmike @robhadfield
const selector = formValueSelector('coach_form');

AthleteProfileForm = connect(state => ({
  FirstName: selector(state, 'athlete_first_name'),
  LastName: selector(state, 'athlete_last_name'),
  Country: selector(state, 'country'),
  DOB: selector(state, 'dob'),
  Gender: selector(state, 'gender'),
  Address: selector(state, 'address'),
  TimeZone: selector(state, 'timezone'),
  MobileNumber: selector(state, 'mobile'),
  Height: selector(state, 'height'),
  Weight: selector(state, 'weight'),
  Bio: selector(state, 'bio'),
  HighSchoolName: selector(state, 'highschool'),
  HighSchoolYear: selector(state, 'highschool_year'),
  HighSchoolUniversity: selector(state, 'highschool_university'),
  HighSchoolProgramLength: selector(state, 'highschool_length'),
  GraduationName: selector(state, 'graduation'),
  GraduationYear: selector(state, 'graduation_year'),
  GraduationUniversity: selector(state, 'graduation_university'),
  GraduationProgramLength: selector(state, 'graduation_length'),
  SportPlayed: selector(state, 'sports_played'),
  SportYear: selector(state, 'practice_year')
}))(AthleteProfileForm);

AthleteProfileForm = reduxForm({
  form: 'coach_form',
  initialValues: {athlete_first_name: {this.props.userData.firstName}}
})(AthleteProfileForm);

here we get error, cannot read props of undefined

how to access props here

**Comment by hluedeke** [comment]
When accessing props, put the initial values in connect
```
connect((state, props) => ({
    ...
    initialValues: {
        athlete_first_name: props.userData ? props.userData.firstName : null,
    }
    ...
})(AthleteForm)
```

instead of in your reduxForm():
```
AthleteProfileForm = reduxForm({
form: 'coach_form',
})(AthleteProfileForm);
```

This question has more to do with [redux-form](https://github.com/erikras/redux-form) than with redux-form-material-ui. Check the documentation at redux-form for more info.

**Comment by hluedeke** [comment]
When accessing props from your component, put initialValues in your connect:
```
connect((state, props) => ({
   ...
   initialValues: {
       athlete_first_name: props.userData ? props.userData.firstName : null,
   }
   ...
})
```
instead of in reduxForm():
```
AthleteProfileForm = reduxForm({
    form: 'coach_form',
})(AthleteProfileForm);
```

**Comment by vaibhav-systango** [comment]
@hluedeke @erikras 

AthleteProfileForm = connect((state, props) => ({
   FirstName: selector(state, 'athlete_first_name'),
  LastName: selector(state, 'athlete_last_name'),
  Country: selector(state, 'country'),
  DOB: selector(state, 'dob'),
  Gender: selector(state, 'gender'),
  Address: selector(state, 'address'),
  TimeZone: selector(state, 'timezone'),
  MobileNumber: selector(state, 'mobile'),
  Height: selector(state, 'height'),
  Weight: selector(state, 'weight'),
  Bio: selector(state, 'bio'),
  HighSchoolName: selector(state, 'highschool'),
  HighSchoolYear: selector(state, 'highschool_year'),
  HighSchoolUniversity: selector(state, 'highschool_university'),
  HighSchoolProgramLength: selector(state, 'highschool_length'),
  GraduationName: selector(state, 'graduation'),
  GraduationYear: selector(state, 'graduation_year'),
  GraduationUniversity: selector(state, 'graduation_university'),
  GraduationProgramLength: selector(state, 'graduation_length'),
  SportPlayed: selector(state, 'sports_played'),
  SportYear: selector(state, 'practice_year'),
   initialValues: {
       athlete_first_name: props.userData ? props.userData.firstName : null,
   }
}))(AthleteProfileForm);

AthleteProfileForm = reduxForm({
  form: 'coach_form'
})(AthleteProfileForm);

I just tried this but this doesn't works out for some reason I don't see initialValues working in the connect block, 

connect((state, props) => ({
   ...
   initialValues: {
       athlete_first_name: 'JON',
   }
   ...
})
Even when i use something like this a text that's hardcode that doesn't works and i don't see initial value JON in my form

Rather it only works when i use it in reduxForm block 
i.e.
AthleteProfileForm = reduxForm({
    form: 'coach_form',
   initialValues:athlete_first_name: 'JON'
})(AthleteProfileForm);

but problem in this case is i only can set hardcoded values and what I want is to access props here

Can you tell what shall I do in this case 
This is my app structure it uses both redux & apollo 
const render = (messages) => {
  ReactDOM.render(
    <ApolloProvider client={client} store={store}>
      <LanguageProvider messages={messages}>
        <Router
          history={history}
          routes={rootRoute}
          render={
            // Scroll to top when going to a new page, imitating default browser
            // behaviour
            applyRouterMiddleware(useScroll())
          }
        />
      </LanguageProvider>
    </ApolloProvider>,
    document.getElementById('app')
  );
};

**Comment by vaibhav-systango** [comment]
![screen shot 2017-05-28 at 7 42 23 pm](https://cloud.githubusercontent.com/assets/25978575/26529474/f2d390d0-43dd-11e7-9e70-83e80b48ccc8.png)
i Can see initial values in react tool with value but i don't see them working on ui

**Comment by vaibhav-systango** [comment]
PFA this file maybe i'm wrapping redux store and apollo client together and that's creating issue:
Please have a look at this
/**
 * app.js
 * This is the entry file for the application, only setup and boilerplate code
 */

// Needed for redux-saga es6 generator support
import 'babel-polyfill';

// Import all the third party stuff
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { applyRouterMiddleware, Router, browserHistory,browserHistoryoute, Redirect,IndexRedirect } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';
import FontFaceObserver from 'fontfaceobserver';
import { useScroll } from 'react-router-scroll';
import 'sanitize.css/sanitize.css';


// Import root app
import App from 'containers/App';

// Import selector for `syncHistoryWithStore`
import { makeSelectLocationState } from 'containers/App/selectors';

// Import Language Provider
import LanguageProvider from 'containers/LanguageProvider';

// Load the favicon, the manifest.json file and the .htaccess file
/* eslint-disable import/no-webpack-loader-syntax */
import '!file-loader?name=[name].[ext]!./favicon.ico';
import '!file-loader?name=[name].[ext]!./manifest.json';
import 'file-loader?name=[name].[ext]!./.htaccess'; // eslint-disable-line import/extensions
/* eslint-enable import/no-webpack-loader-syntax */

import configureStore from './store';

// Import i18n messages
import { translationMessages } from './i18n';

// Import CSS reset and Global Styles
import './global-styles';

// Import routes
import createRoutes from './routes';

// Apolo Client 
import ApolloClient, { createNetworkInterface } from 'apollo-client'
import { ApolloProvider } from 'react-apollo'
import injectTapEventPlugin from 'react-tap-event-plugin';
// Apolo Client

const networkInterface = createNetworkInterface({
  uri: 'https://api.graph.cool/simple/v1/cj32ti8u8khzz0122jd4cwzh6',
});

networkInterface.use([{
  applyMiddleware(req, next) {
    if (!req.options.headers) {
      req.options.headers = {};  // Create the header object if needed.
    }
    // get the authentication token from local storage if it exists
    const token = localStorage.getItem('token');
    req.options.headers.authorization = token ? `Bearer ${token}` : null;
    next();
  }
}]);

const client = new ApolloClient({
  networkInterface,
});


injectTapEventPlugin();

// Observe loading of Open Sans (to remove open sans, remove the <link> tag in
// the index.html file and this observer)
const openSansObserver = new FontFaceObserver('Open Sans', {});

// When Open Sans is loaded, add a font-family using Open Sans to the body
openSansObserver.load().then(() => {
  document.body.classList.add('fontLoaded');
}, () => {
  document.body.classList.remove('fontLoaded');
});

// Create redux store with history
// this uses the singleton browserHistory provided by react-router
// Optionally, this could be changed to leverage a created history
// e.g. `const browserHistory = useRouterHistory(createBrowserHistory)();`
const initialState = {};
const store = configureStore(initialState, browserHistory);

// Sync history and store, as the react-router-redux reducer
// is under the non-default key ("routing"), selectLocationState
// must be provided for resolving how to retrieve the "route" in the state
const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: makeSelectLocationState(),
});

// Set up the router, wrapping all Routes in the App component
const rootRoute = {
  component: App,
  childRoutes: createRoutes(store),
};
//add provider with apollo provider if later there's react-intl issue for provider
const render = (messages) => {
  ReactDOM.render(
    <ApolloProvider client={client} store={store}>
      <LanguageProvider messages={messages}>
        <Router
          history={history}
          routes={rootRoute}
          render={
            // Scroll to top when going to a new page, imitating default browser
            // behaviour
            applyRouterMiddleware(useScroll())
          }
        />
      </LanguageProvider>
    </ApolloProvider>,
    document.getElementById('app')
  );
};

// Hot reloadable translation json files
if (module.hot) {
  // modules.hot.accept does not accept dynamic dependencies,
  // have to be constants at compile-time
  module.hot.accept('./i18n', () => {
    render(translationMessages);
  });
}

// Chunked polyfill for browsers without Intl support
if (!window.Intl) {
  (new Promise((resolve) => {
    resolve(import('intl'));
  }))
    .then(() => Promise.all([
      import('intl/locale-data/jsonp/en.js'),
      import('intl/locale-data/jsonp/de.js'),
    ]))
    .then(() => render(translationMessages))
    .catch((err) => {
      throw err;
    });
} else {
  render(translationMessages);
}

// Install ServiceWorker and AppCache in the end since
// it's not most important operation and if main code fails,
// we do not want it installed
if (process.env.NODE_ENV === 'production') {
  require('offline-plugin/runtime').install(); // eslint-disable-line global-require
}

**Comment by hluedeke** [comment]
I think maybe your calls are backwards, too. Try putting the reduxForm() code before the connect() code, and see if that works.

**Comment by vaibhav-systango** [comment]
@hluedeke  @erikras 
I tried this too, it doesn't work still.
Can you please provide any other solution

**Comment by robhadfield** [comment]
@vaibhav-systango - in the below image your values are not correct. The values should be an object structure:

eg:
```initialValues: {
    athlete_first_name: 'John'
}```

You are not creating the reference - 'athlete_first_name' and 'John' are two separate values of an array.

https://cloud.githubusercontent.com/assets/25978575/26529474/f2d390d0-43dd-11e7-9e70-83e80b48ccc8.png

**Comment by robhadfield** [comment]
Here's a complete piece (apart from the component) of code that I use with success.

`GroupForm = reduxForm({
    form: 'EditGroup'
})(GroupForm);

const mapStateToProps = (state, ownProps) => {

    // Here you have access to state and also any props you have passed to the form through 'ownProps'.

    let returnObject = {};

    // Add Initial values
     returnObject.initialValues = {
        name: state.group.groupname, // These could be from ownProps too
        type: state.group.grouptype
    };

    return returnObject;
};

const mapDispatchToProps = dispatch => {
    return { dispatch };
};

export default connect(mapStateToProps, mapDispatchToProps)(GroupForm);`

**Comment by vaibhav-systango** [comment]
@robhadfield thanks for your suggestion, that didn't work I finally have a solution to this:
@hluedeke  @erikras

Using initialize function & setting enableReinitialize param to true in form works great

class AthleteProfileForm extends Component {
  static propTypes = {
    initialize: React.PropTypes.func.isRequired
  }

  componentDidMount() {
    this.props.initialize(this.props.userData)
  }
  render() {

    const {loading, error, repos, handleSubmit, pristine, reset, submitting, sportsList, userData, initialValues} = this.props;
    return (
      <form>
      .....
      </form>
    );
  }
}

AthleteProfileForm = reduxForm({
  form: 'athlete_profile_form',
  enableReinitialize: true,
})(AthleteProfileForm);

AthleteProfileForm = connect((state, ownProps) => ({  
  FirstName: selector(state, 'athlete_first_name')
}))(AthleteProfileForm);

export default AthleteProfileForm;

**Comment by robhadfield** [comment]
Glad you got it working - I did add the `enableReinitialize: true` into my answer after I removed it in error.
