### ISSUE TITLE
redux form material ui work in react native?

### ISSUE THREAD

**Issue by ckim16** [erikras/redux-form-material-ui#156]
I wanted to use import `{ RadioButton, RadioButtonGroup } from 'redux-form-material-ui';` but it gives me an error saying `Unable to resolve module 'react-dom' from 'file/path/material-ui/AutoComplete/AutoComplete.js'.....` Can I use redux form material ui in reant native or do I have to install more modules to be able to use it?

Please let me know if anyone has had similar issue as mine.

Thank you,

**Comment by Undeadlol1** [comment]
This PR might solve your problems, because when you export RadioButton it will not also export AutoComplete, which relies on react-dom.
https://github.com/erikras/redux-form-material-ui/pull/157
Wait till it's merged.

**Comment by mihirsoni** [comment]
This has been fixed and released with v4.3.0. This should be fixing the import error now.
