### ISSUE TITLE
any way to override the style of each components?

### ISSUE THREAD

**Issue by mauvew** [erikras/redux-form-material-ui#16]
Just wondering,  any possible solution to override the style of the component?

for instance, override the style of TextField?

**Comment by erikras** [comment]
This is a question for the Material UI repo. Not here.

This library passes along all the props you give it to Material UI.

**Comment by mauvew** [comment]
Thanks a lot, this actually answered my question. I understand how to override the style in MUI, just didn't realize it passes the props to MUI components. 👍
