### ISSUE TITLE
Support v1

### ISSUE THREAD

**Issue by gfpacheco** [erikras/redux-form-material-ui#165]
Material-UI is working on it's v1, it should be a good idea to start working to support that.

In fact I'm already [working on it](https://github.com/gfpacheco/redux-form-material-ui/tree/v1-alpha), and I'll open a PR when I think it's stable, but I guess it should be kept in a separate branch until v1 gets released.

**Comment by diegolaciar** [comment]
I need V1 support.
@gfpacheco thanks. Can you push that branch ?
@erikras any update on this ?

**Comment by gfpacheco** [comment]
I don't wanna open a PR to branch master while MaterialUI v1 is in alpha/beta. But if they create another branch I would be happy to create it.

For now I guess you can use `@gfpacheco/redux-form-material-ui` at version `v1.0.0-alpha.2`:

```
npm install --save @gfpacheco/redux-form-material-ui@v1.0.0-alpha.2
```

**Comment by gfpacheco** [comment]
Just an update: MaterialUI is now in beta and also is my fork. The latest version is `v1.0.0-beta.1`.

```
npm install --save @gfpacheco/redux-form-material-ui@v1.0.0-beta.1
```

**Comment by tatemz** [comment]
Is there an update on this becoming a PR?

**Comment by gfpacheco** [comment]
If @erikras creates a `v1-beta` branch I would open a PR to it. But I don't think opening a PR to the master would be a good idea right now.

**Comment by suryaiiit** [comment]
CheckBox isn't working, DatePicker/TimePicker are yet to ported to V1, even the SelectField.

**Comment by oallouch** [comment]
SelectPicker is here.

**Comment by Sigfried** [comment]
Any update on this? I've got `"@gfpacheco/redux-form-material-ui": "v1.0.0-beta.1",` in my dependencies but having various problems.

My problem of the moment is with SelectField, which, I guess is now called Select in material-ui v1, but I'm not sure what to import from redux-form-material-ui.

**Comment by gfpacheco** [comment]
@Sigfried Sorry, the Select component is new and I still lack support for it. I'll be glad to review a PR implementing that support, or you could wait a couple days, I'll find some time to add it to my package.

**Comment by Sigfried** [comment]
Thanks, @gfpacheco! Sorry to be lame, but I'll wait for you to do it. My code has a fairly endless supply of bugs for me to work on in the meantime ;)

**Comment by mihirsoni** [comment]
@gfpacheco  Do you mind creating PR for a different branch ?

**Comment by gfpacheco** [comment]
Of course not, which one should I create to? I guess I can't create a PR to a branch that doesn't exist.

**Comment by mihirsoni** [comment]
@gfpacheco  I have created branch 5.0. You can create PR on that.

**Comment by gfpacheco** [comment]
@Sigfried I still didn't really test it in a real project, but I guess the Select component is working on the new version:

```
npm install --save @gfpacheco/redux-form-material-ui@v1.0.0-beta.3
```

**Comment by KamesCG** [comment]
Thanks for the update.

I think it might be worthwhile to add backwards compatibility for TimePicker, DataPicker and Slider in Redux-Form-Material-UI repo. The new Material UI doesn't provide default components for these types now, but it would still be nice to have the redux-form-material-ui provider a wrapper for those components.

**Comment by mihirsoni** [comment]
Thanks all for your patients. It is now released under as next release.

To use : 

```bash
npm install --save redux-form-material-ui@next
```

Currently in beta , after few weeks will move it to latest tag. Release notes [here](https://github.com/erikras/redux-form-material-ui/releases/tag/v5.0.0-beta-1) 

Documentation and examples can be found [here](https://github.com/erikras/redux-form-material-ui/tree/5.0)
