### ISSUE TITLE
How to display validation failure for MUI Checkbox?

### ISSUE THREAD

**Issue by j18ter** [erikras/redux-form-material-ui#169]
The Checkbox component in redux-form-material-ui does not display validation errors. I tried creating a custom Checkbox component, but was utterly unsuccessful with the Checkbox from either material-ui or redux-form-material-ui as the starting point. Any suggestions how one can create a custom component from material-ui Checkbox that displays validation errors with redux-form?

**Comment by j18ter** [comment]
Attempting to do this with a function like `renderField` from the examples failed miserably, but here is how I ended up doing it:
```
import React from 'react';
import { Checkbox } from 'redux-form-material-ui';
const styles = {
    error: {
        color: 'red',
        fontSize: 'small'
    }
};
class ValidatedCheckbox extends Checkbox {
    render() {
        const {meta: {touched, error}} = this.props;
        return (
            <div>
              {super.render()}
              {touched && error && <span style={styles.error}>{error}</span>}
            </div>
        );
    }
}
```

**Comment by mihirsoni** [comment]
It seems you have solved this.

**Comment by tandonrajiv** [comment]
I am unable to add validation on checkbox can you please create a small form with this checkbox.

**Comment by pauloruizcares** [comment]
`<Checkbox
      style={{
        color: error ? "red" : undefined
      }}
 />`
