### ISSUE TITLE
RadioButton, CheckBox, Toggle not working

### ISSUE THREAD

**Issue by gorans90** [erikras/redux-form-material-ui#171]
Hi there,
I have problem with radiobutton, checkbox and toggle. They are rendering but when I click on some of them nothing happen. What could I miss?
Here is my code:

```
 <div>
   <Field name='delivery' component={RadioButtonGroup}>
     <RadioButton value='pickup' label='Pickup' />
     <RadioButton value='delivery' label='Delivery' />
   </Field>
 </div>

<div>
  <Field
     name='thinCrust'
     component={Toggle}
     label='Thin Crust'
     labelPosition='right'
    />
 </div>
 <div>
   <Field name='pepperoni' component={Checkbox} label='Pepperoni' />
 </div>
```

I want to mention that I also imported injectTapEventPlugin and init it.

Hope you can help me.

**Comment by tmartensen** [comment]
I'm having a similar issue where I can see that the radio button is being clicked and the state is changing in the form reducer, but the `RadioButton` is not being selected.

**Comment by KrzysztofKarol** [comment]
Same problem.
I think this causes the problem https://github.com/callemall/material-ui/issues/7766

**Comment by mihirsoni** [comment]
@gorans90  closing this as it is an issue over https://github.com/callemall/material-ui/issues/7766

Please feel free to reopen this if it's issue with this library.
