### ISSUE TITLE
It's not clear how Validate works..

### ISSUE THREAD

**Issue by Ivan-Parushev** [erikras/redux-form-material-ui#172]
When trying to pass a function directly inside Validate property like so:
`<Field ...other validate={(value) => value == null ? "required" : undefined} />`
It doesn't work.

They only way that it works is to use it like it is show in the example: 
```
const validateRequired = (value) => {
  return value == null ? "required" : undefined;
}
class myForm extends React.Component {
  render(){
     return (<form><Field ...other validate={validateRequired} /></form>)
  }
}
```
The only problem is that I want to either be able to pass variables to validateRequired or define the validating function inside myForm component. The reason for this is because I want to use react-i18next library for translating the text inside the validating functions and that is possible only inside the component. 

```
class myForm extends React.Component {
  let { t } = this.props;
  render(){
     return (<form><Field ...other validate={(value) => value == null ? t('myForm.required) : undefined} /></form>)
  }
}

or

class myForm extends React.Component {
  render(){
    let { t } = this.props
    const validateRequired = (value) => {
      return value == null ? t('myForm.required) : undefined;
    }
     return (<form><Field ...other validate={validateRequired} /></form>)
  }
}
```

Or maybe I am just a moron. Please help!

**Comment by mihirsoni** [comment]
I just tested with latest ```redux-form```. It should work. Could you please verify ? I am closing this for now, feel free to reopen if still issue occurs.
