### ISSUE TITLE
Unable to enter text inside Textfield using material redux form

### ISSUE THREAD

**Issue by alrms** [erikras/redux-form-material-ui#177]
Hello everyone, i'm having an issue using Textfield. To begin with my code is:

```js
import React, { PropTypes } from 'react';
import { Field } from 'redux-form/immutable';
import { TextField } from 'redux-form-material-ui';
import Divider from 'material-ui/Divider';
import Menu from 'material-ui/Menu';
import RaisedButton from 'material-ui/RaisedButton';
import { SEARCHVIEW_HINT_CIF,
          SEARCHVIEW_HINT_AFM,
          SEARCHVIEW_SEARCH
} from '../../common/constants';

const SearchDefaultView = (props) => {
  const { requestCustomerInfo, handleSubmit } = props;
};

 return (
    <form onSubmit={handleSubmit(requestCustomerInfo)}>
        <Field
          id="searchCif"
          name="searchCif"
          label="searchCif"
          component={TextField}
          floatingLabelText={SEARCHVIEW_HINT_CIF}
          floatingLabelFixed={false}
        />
        <Field
          id="searchAFM"
          name="searchAFM"
          component={TextField}
          floatingLabelText={SEARCHVIEW_HINT_AFM}
          floatingLabelFixed={false}
        />
        <RaisedButton
          type="submit"
          fullWidth
          primary
          label={SEARCHVIEW_SEARCH}
        />
      </Menu>
    </form>
  );

SearchDefaultView.propTypes = {
  requestCustomerInfo: PropTypes.func,
  handleSubmit: PropTypes.func.isRequired,
};

export default SearchDefaultView;

```
I can't type a text inside the textfield. I also copy and paste the code from here http://redux-form.com/6.8.0/examples/material-ui/. The versy weird part is that the textfield and select components are not showing the text. In textfield i cannot even add text. I've check the actions that dispatched and 
in textfield only ONFOCUS & ONBLUR are triggered. Not the ONCHANGE as the in checkbox and radio button. I've spent 2 days figuring out what's happening and still cant find what is going wrong.

**Comment by alrms** [comment]
<form onSubmit={handleSubmit(requestCustomerInfo)}>
        <Field
          id="searchCif"
          name="searchCif"
          label="searchCif"
          component={TextField}
          floatingLabelText={SEARCHVIEW_HINT_CIF}
          floatingLabelFixed={false}
        />
        <Field
          id="searchAFM"
          name="searchAFM"
          component={TextField}
          floatingLabelText={SEARCHVIEW_HINT_AFM}
          floatingLabelFixed={false}
        />
        <RaisedButton
          type="submit"
          fullWidth
          primary
          label={SEARCHVIEW_SEARCH}
        />
      </Menu>
    </form>

**Comment by mihirsoni** [comment]
You've not connected your form with redux at all the state is not being maintained for the Component. 

Please follow example http://erikras.github.io/redux-form-material-ui/

Please feel free to reopen if it doesn't work.
