### ISSUE TITLE
Problem with valueLink parameter comes with React 16 alpha

### ISSUE THREAD

**Issue by dekhanov-vladislav-yumasoft** [erikras/redux-form-material-ui#182]
From React 16 alpha you would see in the changelogs that `valueLink` parameter is removed.
Here is PR: https://github.com/facebook/react/pull/8165/files
Do you have any ideas or work in close future how to avoid this kinda errors?
![Error example](https://i.gyazo.com/03dc94c14495925e971498557ac5e292.png)

**Comment by mihirsoni** [comment]
This isn't part of redux-form-material UI it is part of material-ui. I can see it has been already remove can you upgrade your version to latest?

I am closing this for now. Feel free to reopen.
