### ISSUE TITLE
compile error  when use branch 5.0 with  material-ui@next 

### ISSUE THREAD

**Issue by ferdinandfly** [erikras/redux-form-material-ui#185]
package.json: 
```
"dependencies": {
    "axios": "0.16.2",
    "lodash": "4.17.4",
    "material-ui": "^1.0.0-beta.16",
    "promise": "8.0.1",
    "react": "15.6.1",
    "react-dom": "15.6.1",
    "react-intl": "2.4.0",
    "react-intl-redux": "0.6.0",
    "react-redux": "5.0.6",
    "react-router": "4.1.2",
    "react-router-dom": "4.1.2",
    "react-router-redux": "^5.0.0-alpha.6",
    "redux": "3.7.2",
    "redux-form": "7.1.1",
    "redux-form-material-ui": "https://github.com/erikras/redux-form-material-ui/tarball/5.0",
    "redux-logger": "3.0.6"
  },
```

ERROR in ./node_modules/redux-form-material-ui/src/Select.js
Module parse failed: xxxx/node_modules/redux-form-material-ui/src/Select.js Unexpected token (6:36)
You may need an appropriate loader to handle this file type.
|
| export default createComponent(Select, ({
|   input: { onChange, value, onBlur, ...inputProps },
|   onChange: onChangeFromField,
|   defaultValue,
 @ ./node_modules/redux-form-material-ui/src/index.js 3:0-44

**Comment by mihirsoni** [comment]
You can now use it from npm it self.

Install with npm like this :
```bash
npm install --save redux-form-material-ui@next
```
