### ISSUE TITLE
Slider resets when it loses focus

### ISSUE THREAD

**Issue by wakusoftware** [erikras/redux-form-material-ui#19]
I have a controlled slider (with a state). But it resets to the beginning when it loses the focus, note that the value maintains itself

```
constructor(props) {
     super(props);
     this.state = {
       salarioSlider: 0
     };
   }

  handleSalarioSlider(value) {
    this.setState({salarioSlider: value});
  }
```

```
<Field name="salario" component={Slider}
                      min={0}
                      max={100000}
                      defaultValue={0}
                      step={1000}
                      style={styles.slider}
                      value={this.state.salarioSlider}
                      onChange={this.handleSalarioSlider.bind(this)}
 />
 <div className="texto-slider">{'Bs. ' + this.state.salarioSlider}</div>
```

Here is a [Snapshot](https://cloud.githubusercontent.com/assets/19551768/17080065/8c64cfca-50f0-11e6-8240-58a9a47b24f8.png)

Any thoughts??

**Comment by wakusoftware** [comment]
Ok I understand it happens because I am overriding "onChange", but how can I access the value of Slider?

**Comment by erikras** [comment]
With a [`formValueSelector()`](http://redux-form.com/6.0.0-rc.4/examples/selectingFormValues/).
