### ISSUE TITLE
How change the fontSize of TextField

### ISSUE THREAD

**Issue by aislanmaia** [erikras/redux-form-material-ui#193]
I'm struggling to change this simple thing.

Changing by className is not enough as it didn't get applied.
For UX reason, I'm trying to increase the size because it's too small.
Already trying to get FormControl, InputLabel and Input to modify its classes by it's hard because the elements itself get out of sync in your spacing calculations.

Somebody can help me out, please ??

**Edit**:  _I'm using the Material-UI 1.0-beta and `redux-form-material-ui@next`_

**Comment by lexparsimonet** [comment]
You must pass the correct properties to the component, if you are having trouble with the `inputStyle` prop causing your `inputStyle` text to overlay the text labels and cause the alignment issues I think you are describing by saying out of 'sync' then it is just a matter of including the props from the material-ui  - [TextField page](http://www.material-ui.com/#/components/text-field) . 

Check the example below, prop values I picked are arbitrary but larger than the defaults for `TextField`.  You probably need add `hintStyle={{ height: 'some numerical value here' }}` to line up the `hintText`. Material-ui renders a `<div>` root element wrapped around the `<label>` elements, each piece of the `TextField` component has to be adjusted. 

`<Field name="foo" 
   component={TextField}
   style={{ height: '150px' }}
   inputStyle={{ fontSize: '1.5rem' }}
   props={{ floatingLabelText: 'Name', hintText: 'Your full name.', autoFocus: true }}
/>`

**Comment by aislanmaia** [comment]
Thanks @lexparsimonet for your kind reply. Below is my attempt to get it working:

```
<Field
    name="email"
    type="email"
    component={TextField}
    placeholder="Email"
    ref={this.saveRef}
    withRef
    style={{ height: "150px "}}
    inputStyle={{ fontSize: '1.6rem' }}
    props={{
        floatingLabelText: 'Email',
        hintText: 'Digite sua senha',
        autofocus: true
    }}
/>
```
One thing that maybe makes more sense, I'm using the Material-UI 1.0-beta and `redux-form-material-ui@next`

Trying this code above but the inputStyle object doesn't get applied either.

Here is a print to details:
![textfield problem](https://user-images.githubusercontent.com/2199137/32692099-e5c79f12-c6f0-11e7-8880-ac522355f2b7.png)


![textfield problem 2](https://user-images.githubusercontent.com/2199137/32692135-63637e32-c6f1-11e7-938a-45bfc8321a07.png)

Just only the `style` prop is getting applied as expected. Any thoughts ? Thanks again!!!

**Comment by lexparsimonet** [comment]
**That is what you get for using beta distributions...and not reading the documents, or stating your distribution version when asking for help** - The 1.0-beta of Material-UI has a different syntax requirements for overriding inline-styles for rendered elements. See [Material-UI Docs for v1-beta, customization/overrides/ ](https://material-ui-next.com/customization/overrides/) or or or.... use the more complex but far superior CSS in JS methodology.

**Comment by aislanmaia** [comment]
Thank for your help @lexparsimonet . I've already accomplished through the `inputClassName` prop that I overlooked in the [docs](https://material-ui-next.com/api/text-field/).
CSS in JS is nice and I'm just beginning to learn how to use it and I'm liking it a lot.

**Comment by kennblvnp** [comment]
in 2020 this doesnt work:


InputProps={{
   classes: {
     input: {fontSize:1},
   },
]}}

**Comment by Tesfit12** [comment]
definitely it is not working.
