### ISSUE TITLE
V 4.3.0 not have index.d.ts file for typescript

### ISSUE THREAD

**Issue by yvanwangl** [erikras/redux-form-material-ui#196]
@erikras I found in the issue #74 you commit a declare file for typescript. But when i install v 4.3.0, there does not have a index.d.ts file.

**Comment by mihirsoni** [comment]
@yvanwangl  Could you try now with 4.3.1 and confirm ?

**Comment by yvanwangl** [comment]
@mihirsoni There does have a index.d.ts file in the v 4.3.1. Thanks for your work.
But i got another error. I found in the index.d.ts file:
```
...
export class AutoComplete extends React.Component<__MaterialUI.AutoCompleteProps, any> {}
```
while `__MaterialUI.AutoCompleteProps<DataItem>` is a Generic type  which need a type parameter .

**Comment by mihirsoni** [comment]
@yvanwangl  Do you mind for PR if you have fix ready ?

**Comment by yvanwangl** [comment]
@mihirsoni Sorry for reply so latter. I have made a PR #198 . Please review my PR  : )

**Comment by mihirsoni** [comment]
@yvanwangl  This has been fixed and released.
