### ISSUE TITLE
'Can't resolve 'material-ui/AutoComplete'

### ISSUE THREAD

**Issue by MaeDae11** [erikras/redux-form-material-ui#199]
Hello! 

Still new to programming, and I'm not quite sure what to do. This is the error I keep getting as soon as I download redux-form-material-ui and start importing section from this repo. I don't have a single file asking about autocomplete.

./node_modules/redux-form-material-ui/lib/AutoComplete.js
Module not found: Can't resolve 'material-ui/AutoComplete' in ...'/node_modules/redux-form-material-ui/lib'

```js
_Imported_
import React from 'react';
import PropTypes from 'prop-types';

// redux validation form for material UI
import { Field, reduxForm } from 'redux-form';
import {
  AutoComplete,
  Checkbox,
  SelectField,
  TextField,
} from 'redux-form-material-ui';

// material UI
import { withStyles } from 'material-ui/styles';
import Input, { InputLabel, InputAdornment } from 'material-ui/Input';
import { MenuItem } from 'material-ui/Menu';
import FileUpload from 'material-ui-icons/FileUpload';
import Button from 'material-ui/Button';
import Typography from 'material-ui/Typography';

```
```
_package.json_
"material-ui": "^1.0.0-beta.21"
"redux-form-material-ui": "^4.3.1"
"react": "^16.1.1"
```
please help!

**Comment by lexparsimonet** [comment]
`Auto Complete` was a module in the material-ui v0.19.4 spec, it appears in the material-ui 1.0.0-**beta** release that the former `Auto Complete` module has been deprecated and the usage moved to a property based on the relative components API - accepting either a _string_ or a _Boolean_ value. (Pulled from the 1.0.0 **beta** [docs](https://material-ui-next.com/demos/text-fields/). For example:

`<TextField 
id="password"
          label="Password"
          className={classes.textField}
          type="password"
          **autoComplete="current-password"**
          margin="normal"
/>`

Furthermore, in the material-ui 1.0.0 **beta** documents there is a section for `Autocomplete` component API which immediately references usage of the `react-autosuggest` npm pacakge, find that [here](https://github.com/moroshko/react-autosuggest). The material-ui docs are written in somewhat poor context to their usage, but alas, this is why I bolden **beta** as this is what to expect from incomplete distributions. `react-auto-suggest` accepts a statement with an object to populate the relative component/`<TextField>` that I suspect you are trying to implement given you code example. If you would like to cease the error you have experienced when you are compiling, remove the v0.19.4 reference to import `AutoComplete` as it does not correlate to the version of material-ui you are using. 

Also, for someone 'new to programming' you have an awful lot of git repo's/commits. Suppose new is 'relative' in this case. Hope my input helps some.

**Comment by MaeDae11** [comment]
Thank you for the help! I really appreciate it.

As for my GitHub, I recently attended a coding bootcamp June to October, so
I pretty much lived and breathed coding. Now I'm a full fledged software
engineer! So newish I guess :)


Respectfully,

Katherine Lane

<https://github.com/MaeDae11>
<https://www.linkedin.com/in/katherine-lane/>
<https://medium.com/@katherinelane11>

**Comment by mihirsoni** [comment]
@MaeDae11 if you want to use MUI beta version you can download redux-form-material-ui@next which supports MUI latest version.

New version of MUI has changed significantly so we have major version bump.

Please feel free to reopen in case of issue still persist.

**Comment by dln88** [comment]
"https://material-ui.com/components/autocomplete/#autocomplete"
This is how material-ui import Autocomplete. But i still got the error: Module not found: Can't resolve '@material-ui/lab/Autocomplete'
I can not get it.

**Comment by ezhimakov** [comment]
> "https://material-ui.com/components/autocomplete/#autocomplete"
> This is how material-ui import Autocomplete. But i still got the error: Module not found: Can't resolve '@material-ui/lab/Autocomplete'
> I can not get it.

same

**Comment by yuval-netanel** [comment]
> > "https://material-ui.com/components/autocomplete/#autocomplete"
> > This is how material-ui import Autocomplete. But i still got the error: Module not found: Can't resolve '@material-ui/lab/Autocomplete'
> > I can not get it.
> 
> same

Same

**Comment by ahmadk1987** [comment]
use: npm install @material-ui/lab --save
and try again

**Comment by NatalyaDol** [comment]
> use: npm install @material-ui/lab --save
> and try again

It's resolved this problem
