### ISSUE TITLE
React 16 support?

### ISSUE THREAD

**Issue by skhg** [erikras/redux-form-material-ui#202]
Do you have plans to add react v16 support? We depend on redux-form-material-ui for some parts of our app, and during a recent upgrade of our core libraries we noticed that this package is limited to react v15.

We have however continued to use this package alongside react v16, even though it warns about missing peer dependencies, it does not seem to cause any problems.

**Comment by mihirsoni** [comment]
@skhg Thanks for reporting the issue. 

Are you using which MUI beta ?

Also, if you're already using with React16 and would be great if you could submit PR.

**Comment by skhg** [comment]
Thanks for merging my pull request #203 . We will be looking forward to the next release on npm!

**Comment by mihirsoni** [comment]
I have released it with 4.3.2 version
