### ISSUE TITLE
How do I use MUI Input component?

### ISSUE THREAD

**Issue by ilyador** [erikras/redux-form-material-ui#204]
How do I connect this form with redux-form?

"redux-form": "^7.2.0", 
"redux-form-material-ui": "^5.0.0-beta.2"

```
<FormControl fullWidth>
  <InputLabel htmlFor={this.props.colorLabel}>{this.props.colorLabel}</InputLabel>
  <Input
    id={this.props.colorLabel}
    value={this.state.color.substr(1)}
    onChange={this.handleInputChange}
    startAdornment={<InputAdornment position="start">#</InputAdornment>}
    endAdornment={
      <InputAdornment position="end">
        <IconButton onClick={this.handleClick}>
          <div className={classes.color} style={{background: this.state.color}}/>
        </IconButton>
      </InputAdornment>
    }
  />
</FormControl>
```

**Comment by yvanwangl** [comment]
@ilyador In my option, if you want to connect form with redux-form, you should use redux-form's Field component which can find examples in [redux-form document](https://redux-form.com/7.2.0/examples/material-ui/)

**Comment by ilyador** [comment]
@yvanwangl I know, but `Field` supports full components like `InputField`, this is composed component which has all kinds of Material-UI inner components. It doesn't work simply putting it inside `Field` like you do with `InputField` etc.

**Comment by andreapier** [comment]
I'm facing the same issue.  
Maybe we need a new component that wraps `Input`?

**Comment by peterbartos** [comment]
Why this is not directly part of the library as `Input` wrapper?
