### ISSUE TITLE
Update  dependencies

### ISSUE THREAD

**Issue by Oleksander-Derechei** [erikras/redux-form-material-ui#207]
Hi, I am using redux-form-material-ui, and during `npm i` I get:

> redux-form-material-ui@4.3.1 requires a peer of material-ui@^0.19.0 || 1 but none is installed. You must install peer dependencies yourself.
npm WARN redux-form-material-ui@4.3.1 requires a peer of react@15 but none is installed. You must install peer dependencies yourself.

Current react version is 16.

Please, update  dependencies.

**Comment by mihirsoni** [comment]
I have updated it in new version will release this in next version. 

https://github.com/erikras/redux-form-material-ui/blob/7cb667b98219cf41a1eab845e47d84ead56ed0f7/package.json#L78

**Comment by codeannie** [comment]
can this also include material-ui dependency?? the current version is now ^0.20.0

**Comment by mihirsoni** [comment]
@codeannie  Would mind sending PR ?
