### ISSUE TITLE
Cannot tab through SelectField

### ISSUE THREAD

**Issue by petermikitsh** [erikras/redux-form-material-ui#21]
When mixing vanilla material-ui `TextField` components with redux-form-material-ui `SelectField` components, the `SelectField`'s are skipped on keyboard tab.

See below GIF:

![tab](https://cloud.githubusercontent.com/assets/1571918/17234904/b7c28900-54f1-11e6-8053-de162c2a63f9.gif)

**Comment by petermikitsh** [comment]
I've refactored my form to use exclusively wrapped components and I am still seeing this issue.

**Comment by m2mathew** [comment]
This is still an issue with MUI itself. We are experiencing the same thing in our code base. Perhaps looking through the issues at the MUI repo will be helpful. 

https://github.com/callemall/material-ui
