### ISSUE TITLE
[Next] Select Field "Multiple" property doesn't work properly

### ISSUE THREAD

**Issue by RSpicer** [erikras/redux-form-material-ui#212]
I may be doing something wrong, but I don't believe so. Rendering a Select field with the Multiple property gives me the following error:

Material-UI: the `value` property must be an array when using the `Select` component with `multiple`.

This is talking about the value property on the component itself, I believe, and not the MenuItem, so not a whole lot I can show on my end. Based on that alone it seems like the redux-form is passing in a raw value instead of an array of values when faced with the multiple property. If you can lead me in the right direction on how to fix it, I'll definitely make a PR.

If you can look at this tonight, it would be unbelievably appreciated. If not, totally understood. Cheers m8!

```
<Field name="fields" component={Select} multiple fullWidth placeholder="Select your Fields" label="Fields to Compare or Display">
          {this.props.survey.items.map((item) =>
            { return item.type === 'Number' ? (
              <MenuItem value={item.identifier}> 
                <ListItemIcon>
                  <ImportContactsIcon />
                </ListItemIcon>
                {item.label}
              </MenuItem> )
              : null
            }
          )}
        </Field>
```

**Comment by davae1an** [comment]
Having the same issue

**Comment by mihirsoni** [comment]
Hi @RSpicer 

Thank you for reporting issue. So value is being actually passed from what consumer component has passed. 

As an example I have added a Unit test case which demonstrate Select with multiple Option.

https://github.com/erikras/redux-form-material-ui/blob/b18ab7267a2d43488f7e11e21bd76dedd34381fd/src/__tests__/Select.spec.js#L34-L53

Could you take a look at it and let me know ? 

 Please correct me if I have mis understood your question.

**Comment by qalqi** [comment]
+1

**Comment by sergeyfedotov** [comment]
I've solved this issue with the following code:

```js
<Field component={Select} multiple format={value => value || []}...
```

**Comment by sarkistlt** [comment]
same here, fix above doesn't help

**Comment by sarkistlt** [comment]
actually sorry it works with minor change 
```js
format={value => Array.isArray(value) ? value : []}
```

**Comment by mihirsoni** [comment]
Closing this, due to inactivity. Feel free to reopen if issue still persist.

**Comment by d0190535** [comment]
Reopening this, I have the same issue but now I am stuck on how to populate it with initial values

`<Field name='reps' component={SelectField} multiple={true} format={value => value || []} value={[]}>
{users.map(function (user) {
										return <MenuItem key={user.userId} value={user.userId} primaryText={user.firstName + ' ' + user.lastName} />;
})}
</Field>`

The dropdown renders fine but the menu item is not pre-selecting.  Any ideas? Thanks
