### ISSUE TITLE
v 4.3.2 typescript support error

### ISSUE THREAD

**Issue by yvanwangl** [erikras/redux-form-material-ui#219]
@sigmike Hi, I install v 4.3.2 as you make a new release. But i find there does not have a index.d.ts file in `/lib` directory, while v 4.3.1 has the index.d.ts file in `/lib` directory. In my options, that may be coused by build ? Please check and make a new release.

**Comment by mihirsoni** [comment]
@yvanwangl Could you check now, I have now kept it with root. with 4.3.3 instead of lib.

**Comment by yvanwangl** [comment]
@mihirsoni Now it works well as the root directory has the index.d.ts file. Thx for your work : )

**Comment by yvanwangl** [comment]
@mihirsoni But i find the `/es` directory has a `index.d.ts` file too. So ts will report an error:
```
 error TS2300: Duplicate identifier 'AutoComplete'.
```
as the index.d.ts file is duplicate.
