### ISSUE TITLE
DatePicker looses value upon reopening

### ISSUE THREAD

**Issue by luxflux** [erikras/redux-form-material-ui#22]
Right now, if you select a date, the text field is filled with the selected value. As soon as you open the date picker again, it switches to blank and the date picker shows no selected date.

If you compare this to the behaviour of the bare MUI date picker, you will see that the selected date is still in the field and the selected date is marked in the date picker.

For debugging, I tried to use MUI with redux-form directly and it boiled down that this starts to happen if you add the `onBlur`/`onFocus` callbacks. Unfortunately, without this callback the dirty/touched tracking does not work.

Any ideas?

**Comment by erikras** [comment]
Fixed in [`v4.0.0`](https://github.com/erikras/redux-form-material-ui/releases/tag/v4.0.0).
