### ISSUE TITLE
Support for React 16 in redux-form-material-ui v5

### ISSUE THREAD

**Issue by filso** [erikras/redux-form-material-ui#224]
Do you plan to implement this? Thanks!

**Comment by mihirsoni** [comment]
Yes. Would you mind PR if there are any changes ?

**Comment by crypto-titan** [comment]
+1

**Comment by gitrite** [comment]
@mihirsoni I've submitted a PR for this issue

**Comment by prescottprue** [comment]
@gitrite Which PR is it? Looking for this same thing.

**Comment by mihirsoni** [comment]
I have published new version on next, if no issues found will move this changes to master.
