### ISSUE TITLE
Warning: React does not recognize the `transitionAppear` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `transitionappear` instead.

### ISSUE THREAD

**Issue by dsaket** [erikras/redux-form-material-ui#229]
I am using the redux-form-material-ui DatePicker as described in the docs. However it just throws these errors.

React does not recognize the `transitionAppear`, `transitionAppearTimeout`, `transitionEnter` and `transitionEnterTimeout` props on DOM element...

I checked it in the developer tools and these transition properties are actually passing down to the child div from it's parent CSSTransitionGroup.

Due to this, the DatePicker dialog is not working as expected. I have already spent more than a day on this but can't seem to get it working. Please help me out!

![screen shot 2018-02-20 at 9 10 11 pm 2](https://user-images.githubusercontent.com/12226009/36433443-80957c9a-1682-11e8-9df9-d16c62d85497.png)

**Comment by mihirsoni** [comment]
What version of React / MUI you're using?

**Comment by dsaket** [comment]
@mihirsoni 
react@16.2.0
material-ui@0.19.4
redux-form-material-ui@4.3.3

**Comment by julianklumpers** [comment]
I'm having the same issue.
i got the following versions:

react@16.2.0
material-ui@1.0.0-beta.37

**Comment by mihirsoni** [comment]
@dsaket 
It seems this issues should be on MUI side and not on this lib. If you look at code this lib doesn't manipulate any props.

https://github.com/erikras/redux-form-material-ui/blob/6cb4fcefb51204a2a8ac51fed30aa1806fd7fc09/src/DatePicker.js#L5-L19

**Comment by mihirsoni** [comment]
@julianklumpers 

* If you're using MUI beta then you should be using next version of this lib
* Calendar is not yet implemented in this lib, I will take some time on weekend or if you could send PR would be great.

**Comment by dqhung215** [comment]
I do have same problem. Do you have any suggestion?

**Comment by thegregthomp** [comment]
I can reproduce this as well using material-ui 1.x and 5.0+ version of this lib.

**Comment by mihirsoni** [comment]
I have published new version on next, let me know if issue still persist.

Closing this for now, feel free to reopen if issue still persist.
