### ISSUE TITLE
lodash.noop Should Be a Dependency

### ISSUE THREAD

**Issue by timscott** [erikras/redux-form-material-ui#23]
I believe this is a bug:
https://github.com/erikras/redux-form-material-ui/blob/master/package.json#L56

It should be in dependencies, not devDependencies since it's imported here:
https://github.com/erikras/redux-form-material-ui/blob/c485bb706ab384613738e458abd384eb4abb40ef/src/AutoComplete.js#L2

**Comment by erikras** [comment]
Doh. It just shouldn't have been used there.

**Comment by erikras** [comment]
Fixed in [`v4.0.1`](https://github.com/erikras/redux-form-material-ui/releases/tag/v4.0.1).
