### ISSUE TITLE
DatePicker doesn't update `anyToched` value

### ISSUE THREAD

**Issue by Palatnyi** [erikras/redux-form-material-ui#230]
Hi. On certain pages in app I use material-ui DatePicker with  with redux-form. I expect that after I change date in connected DatePicker the value of `anyTouched` will change but it doesn't.
In all other cases `anyTouched` changes value as expected.

**Comment by mihirsoni** [comment]
Closing is due to inactivity. Please feel free to re-open if still is an issue.
