### ISSUE TITLE
Add material-ui as a peer-dependency (version 5.0.0-beta)

### ISSUE THREAD

**Issue by gitrite** [erikras/redux-form-material-ui#233]
In order to prevent issues with packages relying on a different version of material-ui, it seems that material-ui should be added as a peer dependency?

**Comment by hughkolias** [comment]
Agreed - we'd love to see this implemented as well (we are running both material ui's at the moment.)

**Comment by gitrite** [comment]
PR submitted for this issue: https://github.com/erikras/redux-form-material-ui/pull/234

**Comment by mihirsoni** [comment]
Closing this, now 1.0 is peer deps.
