### ISSUE TITLE
redux-form/immutable + Material UI 1.x doesn't work.

### ISSUE THREAD

**Issue by thegregthomp** [erikras/redux-form-material-ui#236]
It doesn't appear that the immutable import from redux-form doesn't work with these wrappers. I haven't tested on the non 1.x. Even if I reference the immutable version of redux-form, everything works, it just returns values as vanilla JS.

**Comment by mihirsoni** [comment]
You need to use redux-form-material-ui@next version. 4.x doesn't support MUI 1.x

**Comment by mihirsoni** [comment]
I am closing this for now, please feel to reopen if issue still persist.
