### ISSUE TITLE
DatePicker not loading the data from my store

### ISSUE THREAD

**Issue by fmaymone** [erikras/redux-form-material-ui#237]
My DatePicker is working perfectly (I got a Date and updated it on my firebase) . 

But when I retrieve the data, it doesnt fill correctly and came blank. 

TO better understanding, it saves everything correctly, but when I will edit my data, it doesnt fill the Field Name with the saved data. 

 ```
<div>
            <Field
              name="title"
              disabled={!initialized}
              component={TextField}
              hintText={intl.formatMessage({ id: 'title_hint' })}
              floatingLabelText={intl.formatMessage({ id: 'title_label' })}
              ref="title"
              withRef
            />
          </div>
          <div>
          <Field name="start_date" component={DatePicker} hintText="Start Date"/>
          </div>
          <div>
          <Field name="end_date" component={DatePicker}  hintText="End Date"/>
          </div>
```

**Comment by mihirsoni** [comment]
MUI 1.0 Doesn't support DatePicker , for that you'll have an option to choose. for example -> https://github.com/dmtrKovalenko/material-ui-pickers
We don't support 0.x now.
