### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by gagarin55** [erikras/redux-form-material-ui#239]
Could someone give me an example how I can use this library in typescript project ?
It doesn't compile at all;(

```
...
import { Field } from 'redux-form';
import { SelectField } from 'redux-form-material-ui';
...

render() {
   return (
              <Field
                name="hui"
                component={SelectField}
              />);
}
```

**Comment by mihirsoni** [comment]
I assume, you must be using redux-form-material-ui@next which currently doesn't support typings.

I am open for the PR, you can take example of [this](https://github.com/erikras/redux-form-material-ui/blob/master/index.d.ts) file and create def file for next version ?

**Comment by mihirsoni** [comment]
Duplicate #223
