### ISSUE TITLE
Consider using material-ui-pickers for date & time pickers

### ISSUE THREAD

**Issue by rooby** [erikras/redux-form-material-ui#269]
The docs for the 5 branch say that date and time pickers are blocked on material ui v1 implementations, however at https://github.com/mui-org/material-ui/issues/4787 it seems that they don't plan to work on that for the foreseeable future and they direct people to use material-ui-pickers.

Would you consider implementing support for material-ui-pickers instead of waiting for the material ui v1 implementation that isn't on the way yet?

**Comment by mihirsoni** [comment]
@rooby  I guess, this library should support what MUI supports any thing which is not supported by MUI will not make sense to integrate as every consumer will have different choice here. 

I am closing this as part of question , if not answered feel free to re-open.
