### ISSUE TITLE
Import/no-unresolved 

### ISSUE THREAD

**Issue by bertdeterd** [erikras/redux-form-material-ui#27]
Hello,

Can import react, material-ui et cetera but only importing redux-form-material-ui is giving me an eslint error.

`import  { TextField }  from 'redux-form-material-ui'; `

'[eslint] Unable to resolve path to module 'redux-form-material-ui'. (import/no-unresolved)'

I have imported the npm package. My package.json is:
`   .....
   "redux": "3.5.2",
   "redux-form": "^6.0.0-rc.4",
   "redux-form-material-ui": "^4.0.1",
    .....`

Not sure where to start looking and why only redux-form-material-ui is giving me this eslint error.

**Comment by bertdeterd** [comment]
Solved it by using:
`import   TextField   from 'redux-form-material-ui/lib/TextField'; `

**Comment by pjhjohn** [comment]
Thanks! This helped me from ignoring rule

**Comment by ckim16** [comment]
I'm using `import { RadioButton, RadioButtonGroup } from 'redux-form-material-ui/lib/RadioButtonGroup';` and it still gives me that `Unable to resolve module...` error.
Any idea?
