### ISSUE TITLE
Any Ideas? 

### ISSUE THREAD

**Issue by Asher978** [erikras/redux-form-material-ui#272]
This is happening with `Toggle` & `Select`. Both are returning this error below:

`The prop component is marked as required in Field, but its value is undefined`

`import { TextField, Toggle } from 'redux-form-material-ui';
`

` 
            <Field
                name="thinCrust"
                component={Toggle}
                label="Thin Crust"
                labelPosition="right"
              />
`

> "redux-form-material-ui": "^5.0.0-beta.2",

> "redux-form": "^7.4.2",

Any suggestions would be much appreciated!

**Comment by morningLemon** [comment]
HI @Asher978 , 

Please see docs & demo here **https://github.com/erikras/redux-form-material-ui/tree/5.0** for [redux-form-material-ui": "^5.0.0-beta.2"].  "component={Toggle}" is undefined as its not an available component in v5.0.

**Comment by Asher978** [comment]
What about the `select`? 
That seems to be included per the docs but same issue as above...

**Comment by morningLemon** [comment]
Hey @Asher978, 

I cant say without seeing an example but you have select referenced incorrectly in your query above. It should be imported and referenced like so: 

import {
  Select
} from 'redux-form-material-ui'

**Comment by Asher978** [comment]
@morningLemon 

Per my original post. I did not get to mention the import of `Select` but below is the import for it and it returns the same error as `Toggle`

`import { Select } from 'redux-form-material-ui';`

**Comment by morningLemon** [comment]
@Asher978, 

I attempted to recreate your issue in CodeSandbox (https://codesandbox.io/s/woo83lzy68) . I think your issue may root from "redux-form-material-ui": "^5.0.0-beta.2". It was giving me issues so I updated to  "redux-form-material-ui": "^5.0.0-beta.3" as seen in the example.

**Comment by Asher978** [comment]
That was it. 
It was the versioning. I didn't see the version instructions anywhere, perhaps its useful to see them in readme for easier integrations.

Appreciate your help!
