### ISSUE TITLE
Question: Dynamic SelectField's

### ISSUE THREAD

**Issue by amalahussein** [erikras/redux-form-material-ui#28]
I have a SelectField whose value should dynamically update another SelectField. I'm using the new v6 syntax, however, I'm unable to get access to the onChange event. Would love a suggestion of how to cleanly implement this. Thank you!

**Comment by adamtal3** [comment]
You can read the current selected values while rendering using the [FormValueSelector](http://redux-form.com/6.0.0-alpha.11/docs/api/FormValueSelector.md) and attaching the current values to the props. Something like this:

```javascript
import { formValueSelector } from 'redux-form'; // or redux-form/immutable

const formSelector = formValueSelector('formname');

const FormWrap= {
  Form: connect((state) => ({ vals: formSelector(state, 'color', 'size') }))(Form)
};
```

Then, while rendering, you can use `this.props.vals.fieldname` to filter your `SelectField` values.

No need for `onChange` here.

**Comment by amalahussein** [comment]
@adamtal3 that's super helpful, and good to know. thanks and closing this now.
