### ISSUE TITLE
How can i change radio button icon color

### ISSUE THREAD

**Issue by scaki** [erikras/redux-form-material-ui#287]
The radio button default comes in turquoise. How do I change his color? I couldn't see it as Props

**Comment by lexparsimonet** [comment]
If you are using the newest spec (3.1.0) then you must decide whether to override the styles inline: 

https://material-ui.com/customization/overrides/#overriding-with-classes 

within each document that contains an element, or by specifying color intention by including a `pallete` object for your applications theme defaults to be overridden. The following URL:

https://material-ui.com/customization/themes/#palette

explains how to use a `pallete` intention object to populate the keys within the element documents, for example : 
```
palette: {
  primary: {
    light: palette.primary[300],
    main: palette.primary[500],
    dark: palette.primary[700],
    contrastText: getContrastText(palette.primary[500]),
  },
  secondary: {
    light: palette.secondary.A200,
    main: palette.secondary.A400,
    dark: palette.secondary.A700,
    contrastText: getContrastText(palette.secondary.A400),
  },
  error: {
    light: palette.error[300],
    main: palette.error[500],
    dark: palette.error[700],
    contrastText: getContrastText(palette.error[500]),
  },
},

```
Also, https://material-ui.com/style/color/ should help to pick a color and organize the key values for your use case. material.io/color codes and hex are supported.
