### ISSUE TITLE
Can update to support latest @material-ui version ?

### ISSUE THREAD

**Issue by shangdev** [erikras/redux-form-material-ui#291]
The supported version is too old now, can I upgrade to the latest version(material-ui)?

Keep up with the times.

**Comment by cdcasey** [comment]
Creating your own wrapper components is pretty easy per the material-ui example in the redux-form docs.

**Comment by shangdev** [comment]
@cdcasey 

Great. I will try it.

**Comment by andelizondo** [comment]
@cdcasey do you have a link or an example of how can I achieve this? 
I updated to the last version of MUI (v4) and this library doesn't work anymore.

**Comment by cdcasey** [comment]
https://redux-form.com/8.2.2/examples/material-ui/

**Comment by andelizondo** [comment]
Thanks! I was looking in the [MUI's docs](https://material-ui.com/components/text-fields/#complementary-projects).

It's so much easier to use `FormControl`! Thanks again!
