### ISSUE TITLE
please update docs

### ISSUE THREAD

**Issue by mayacode** [erikras/redux-form-material-ui#3]
"redux-form": "^6.0.0-alpha.15",
"redux-form-material-ui": "^2.0.0",

copied example from readme gives bunch of errors:

```Warning: Element: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.```

```Warning: Element: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.```

```Warning: Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.```

```Uncaught Invariant Violation: Component(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.```

running example gives an error on `npm install`:

```
    Hash: 5df58aa01ae6cec441a7
    Version: webpack 1.13.1
    Time: 2657ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  85.8 kB       0  [emitted]  main
    bundle.js.map   706 kB       0  [emitted]  main
    [0] multi main 40 bytes {0} [built] [1 error]
    + 298 hidden modules
    
    ERROR in multi main
    Module not found: Error: Cannot resolve 'file' or 'directory' ./src/index in     mypath/node_modules/redux-form-material-ui/example
     @ multi main
```

running example from 'Live Demo' throws an error:
```reduxForm.js:521Uncaught TypeError: Cannot read property 'wrapped' of undefined```

I would appreciate a hint, how to make it work

**Comment by Chris927** [comment]
You may receive this error when you use `reduxForm()` as a React component instead of a higher order function (to be called with a React component):

Instead of

```
Form = reduxForm({ ...});
```

You would rather say

```
Form = reduxForm({ ...})(Form);
```

If I'm not mistaken, the example is incorrect in this regard.

**Comment by erikras** [comment]
Sorry about that. That's why I include the actual code in the live demo, because code that isn't actually run usually ends up with typos like that.

**Comment by Chris927** [comment]
NP, Thanks!
