### ISSUE TITLE
Autocomplete can only select once.

### ISSUE THREAD

**Issue by tbson** [erikras/redux-form-material-ui#39]
From your example about Autocomplete in: http://erikras.github.io/redux-form-material-ui/
After I choose one option then I can't choose another one without page refresh.

**Comment by mpolichette** [comment]
Testing this, it seems like it works fine.  

Note that once you've selected a value, your options are filtered by the selected option's string.   Deleting the current choice make all of the other choices available again.

**Comment by Tushant** [comment]
I have used autocomplete of material-ui with redux form. Even after selecting a value, all other choices are available. But it is not possible with this library. I am not raising any issue. I am just curios to know why it is done that way? 

Thanks
