### ISSUE TITLE
Cannot find module "material-ui/RadioButton"

### ISSUE THREAD

**Issue by pavel06081991** [erikras/redux-form-material-ui#40]
I have this code:

import { Field, reduxForm } from 'redux-form/immutable';
import { TextField } from 'redux-form-material-ui';

and I use [react-boilerplate](https://github.com/mxstbr/react-boilerplate). After building and opening page in browser I get the next error:

`Cannot find module "material-ui/RadioButton"`

I just tried to import TextField and got this issue.

Maybe it is somehow related with this [issue](https://github.com/erikras/redux-form/issues/1637)?

**Comment by pavel06081991** [comment]
I do not know why, but after deleting node_modules folder and running "npm i" it works!

**Comment by erikras** [comment]
`<shrug/>` Glad it's resolved.
