### ISSUE TITLE
Error with TextField

### ISSUE THREAD

**Issue by EQuimper** [erikras/redux-form-material-ui#43]
Hi,  I've just `import { TextField } from 'redux-form-material-ui';` and got this error `createComponent.js:55 Uncaught TypeError: Cannot read property 'name' of undefined`

I never get this error before but today I got it don't know why.

**Comment by EQuimper** [comment]
Version 4.0.1

**Comment by prameet-jain** [comment]
While I was trying out your example page, I got this
`Warning: TextField contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components`

**Comment by henrylingumi** [comment]
@EQuimper Did you solve this issue?

**Comment by EQuimper** [comment]
Yes I solve it

**Comment by khaoptimist97** [comment]
@EQuimper How do you solve it?I get stuck in the same problem
