### ISSUE TITLE
[RadioButtonGroup] How to display errors?

### ISSUE THREAD

**Issue by llopez95** [erikras/redux-form-material-ui#45]
Hi,

I couldn't find a way to display errors on a RadioButtonGroup.

For instance, I have a RadioButtonGroup with no default value that is required.
At the moment, user stucks on the submit button without any proper message.

Did any one found a way to display them?

Best regards,

**Comment by llopez95** [comment]
Okay... sorry for the useless issue, seems like it is related to Material specs that don't specify it.
I'm closing this "issue"...

https://github.com/callemall/material-ui/issues/3771

Regards,

**Comment by dcifuen** [comment]
Even if the Material Design spec doesn't specify it, I consider there should be an easy way to do it using just redux-form-material-ui, maybe providing an additional custom element via props
