### ISSUE TITLE
Can't edit any component

### ISSUE THREAD

**Issue by anykao** [erikras/redux-form-material-ui#46]
When using the latest redux-form-material-ui, my form can't reflect any change.
Do you have any idea?

You can try it here 
[https://github.com/anykao/live-guide2]
npm install
npm start

**Comment by pierreio** [comment]
Same issue here, I'm investigating.

**Comment by pierreio** [comment]
I found my issue. I mounted the reducer to the wrong key. It has to be 'form'.

**Comment by anykao** [comment]
thank you. I will give a try.

**Comment by anykao** [comment]
just as you said.
