### ISSUE TITLE
Prop "format" for TimePicker component interfere with Field components prop

### ISSUE THREAD

**Issue by aludvigsen** [erikras/redux-form-material-ui#49]
To set the format for the TimePicker we use the _format_ prop like this
`<TimePicker format="24hr" />`

How to set prop format when using the Field component?

`<Field name="some_name" component={TimePicker} format="24hr" />` 
This is not working because the Field component already has a prop called _format_.

**Comment by jamieparkinson** [comment]
Not an ideal solution, but you can introduce a new prop (let's say `timeFormat`) that gets converted to `format` in mapProps:
```
createComponent(
  TimePicker,
  ({
    input: {
      onBlur, // eslint-disable-line no-unused-vars
      onChange,
      ...inputProps
    },
    timeFormat,
    ...props
  }) => ({
    ...inputProps,
    ...mapError(props),
    format: timeFormat,
    onChange: (event, value) => onChange(value),
    value: inputProps.value !== '' ? inputProps.value : null
  })
)
```
Where I have also added the last line as per https://github.com/erikras/redux-form-material-ui/issues/37

**Comment by itditp** [comment]
✖   4:16  'createComponent' is not defined  no-undef
  ✖  16:8   'mapError' is not defined

**Comment by itditp** [comment]
Any ideas?

**Comment by tikitikipoo** [comment]
below code works fine
```
              <Field
                name="at"
                component={TimePicker}
                format={null}
                props={{format: "24hr"}}
              />

```

**Comment by mihirsoni** [comment]
Thanks @tikitikipoo  For the help :) Closing this feel free to open if still facing an issue.
