### ISSUE TITLE
Cannot read property 'getRenderedComponent' of undefined

### ISSUE THREAD

**Issue by anthonybrown** [erikras/redux-form-material-ui#54]
I am trying to get `redux-form-material-ui` to work with my app.
I basically copied the code from the `material-ui` demo to see if it worked.
It doesn't.

[Here](https://gist.github.com/anthonybrown/e3e5b15a33646a0223e506d79edabb48) are the files. I have a `index.js` and a `register.js` file in components/auth/ directory.

I commented out the errors check, even though I had all the fields filled out, (I was still getting the errors).
The form still won't send.

Can someone please take a look? 
I need some suggestions.
Thanks so much

**Comment by jupadev** [comment]
Hi @anthonybrown  you are trying to access to a not defined ref, you should use `this.refs.firstName`  instead of  ` this.refs.name` 

Cheers
