### ISSUE TITLE
unable to add a custom action after selecting radion button from radioGroup ?

### ISSUE THREAD

**Issue by iiitmanikanta** [erikras/redux-form-material-ui#55]
i want to make my custom action along with state updation when radio buttion is selected from radioGroup.
            `<Field name={id} component={RadioButtonGroup} onChange={this.handleRadioSelect}>`
              `{radioButtons}`
            `</Field>`
when i write onChange event listener redux form state is not updating ?

**Comment by reggieboyYEAH** [comment]
any update on this?

**Comment by reggieboyYEAH** [comment]
Just an update on this. I managed to make this work after updating to 
redux-form 6.5.0
my redux-form-material-ui is 4.1.2

**Comment by mihirsoni** [comment]
closing this. Thanks for the update @reggieboyYEAH
