### ISSUE TITLE
required prop 'fields' not specified using example code

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [erikras/redux-form-material-ui#56]
Hi, I'm getting this error:
propType: Required prop `fields` was not specified in `ReduxForm(CreateIncident)`. Check the render method of `Connect(ReduxForm(CreateIncident))`
from purely copying and pasting the example code into a class called 'CreateIncident'
Anyone have any idea why this error is being thrown? I assumed the component "Field" was what was specifying the field prop? Thanks

**Comment by ptim** [comment]
maybe a mismatch of versions / incomplete migration? redux-form v5 passed the fields array around: http://redux-form.com/6.4.3/docs/MigrationGuide.md/

**Comment by sammy6464** [comment]
Aah yes that was it thanks a lot!

**Comment by ptim** [comment]
sweet! glad to help - wanna close the issue?
