### ISSUE TITLE
Using RaisedButton component for form submission needs two clicks

### ISSUE THREAD

**Issue by HendrikThePendric** [erikras/redux-form-material-ui#63]
When using a RaisedButton component as submit button in a redux-form controlled form the submit action is only triggered upon the second click. 

Using a plain <button> type="submit" works as expected (handleSubmit is called on the first click).

After attaching an `onClick` handler to the button everything works fine again, so it's not a huge issue. However (to me) this behaviour is not expected. Perhaps it would be good to add a RaisedButton component to this library that triggers the submit on first click.

(code below works in current situation)

```
<RaisedButton
    label="Add contact"
    secondary={true}
    type="submit"
    disabled={pristine || !valid || submitting}
    onClick={handleSubmit}
    />```

**Comment by mohamed-nazim** [comment]
`import React, { Component } from 'react';
import { reduxForm, Field } from 'redux-form'
import RaisedButton from 'material-ui/RaisedButton'
import { TextField } from 'redux-form-material-ui'


const required = value => value==null ?'Required': undefined;

class Login extends Component {
  handleFormSubmit({username, password}) {
    console.log(username, password);
  }

  render () {
    const {handleSubmit, fields: {username, password }} = this.props;


    return (
    <form onSubmit={handleSubmit(this.handleFormSubmit.bind(this))}>
      <Field {...username}
             name="username"
             validate={required}
             component={TextField}
             hintText="Username"/><br />
      <Field {...password} name="password"
             validate={required}
             component={TextField}
             hintText="Password"
             type="password"/><br />
      <RaisedButton
      primary
      type="submit"
      label="Login"
      action="submit"
      //disabled={this.context.validate}
      //onTouchTap={this.context.submit}
      />
    </form>
    )
  }
}

export default reduxForm({
  form: 'login',
  fields: ['username', 'password'],
})(Login)`

**Comment by mohamed-nazim** [comment]
I am working with a Login form and below code works fine:

---- login.js

    import React, { Component } from 'react';
    import { reduxForm, Field } from 'redux-form'
    import RaisedButton from 'material-ui/RaisedButton'
    import { TextField } from 'redux-form-material-ui'
    
    
    const required = value => value==null ?'Required': undefined;
    
    class Login extends Component {
      handleFormSubmit({username, password}) {
        console.log(username, password);
      }
    
      render () {
        const {handleSubmit, fields: {username, password }} = this.props;
    
    
        return (
        <form onSubmit={handleSubmit(this.handleFormSubmit.bind(this))}>
          <Field {...username}
                 name="username"
                 validate={required}
                 component={TextField}
                 hintText="Username"/><br />
          <Field {...password} name="password"
                 validate={required}
                 component={TextField}
                 hintText="Password"
                 type="password"/><br />
          <RaisedButton
          primary
          type="submit"
          label="Login"
          action="submit"
          />
        </form>
        )
      }
    }
    
    export default reduxForm({
      form: 'login',
      fields: ['username', 'password'],
    })(Login)

**Comment by ptim** [comment]
dunno if it helps, but there are several issues in material-ui which deal with double-clicks... here's one: https://github.com/callemall/material-ui/issues/4532
