### ISSUE TITLE
Warning: Failed prop type: Invalid prop `searchText` of type `object` supplied to `AutoComplete`, expected `string`.

### ISSUE THREAD

**Issue by sameera-rez** [erikras/redux-form-material-ui#67]
I am using autocomplete component and i am getting following error

`Warning: Failed prop type: Invalid prop searchText of type object supplied to AutoComplete, expected string.`

The dataSource privided hs following shape

[{id: "141", name: "david", country: 'us' }, {id: "142", name: "Jon", country: 'uk' }]

**Comment by danielterwiel** [comment]
Your `dataSource` is not following the material-ui interface: 

> [{id: "141", name: "david", country: 'us' }, {id: "142", name: "Jon", country: 'uk' }]

should be

> [{value: "141", text: "david", country: 'us' }, {value: "142", text: "Jon", country: 'uk' }]

The `dataSourceConfig` property appears to be [bugged](https://github.com/erikras/redux-form-material-ui/issues/24) so there's no out of the box solution to solve that issue

**Comment by baldman** [comment]
This also happened to me with 4.2.0, the solution was to actually use dataSourceConfig, even when I was using the default shape of the object, that is with `value` and `text` attributes. Also possibly related to #98 and #24

**Comment by fallanic** [comment]
same, I needed to add `dataSourceConfig={{ value: 'value', text: 'text' }}` to my Field declaration.

Thanks @baldman !

**Comment by mihirsoni** [comment]
It seems it has been worked out.

Closing this as of now.

If issue still persist feel free to reopen.
