### ISSUE TITLE
Boolean values for RadioButtons

### ISSUE THREAD

**Issue by d-winter** [erikras/redux-form-material-ui#72]
Hi,

I have noticed, that RadioButtons with boolean values are saved as strings in redux.
Eg.:

```
<Field name='booleanTest' component={RadioButtonGroup}>
  <RadioButton
     value
     label='shouldBeTrue'
  />
  <RadioButton
    value={false}
     label='shouldBeFalse'
  />
</Field>
```
Is this the desired behaviour? It's not a very elegant way to parse the strings later back into boolean so any help would be awesome.

**Comment by erikras** [comment]
Try adding `format={null}`

See: #37 

http://stackoverflow.com/questions/40492077/setting-a-defaultvalue-for-timepicker-using-redux-form-and-materialui

**Comment by d-winter** [comment]
Hmm, solved with parse={val => val === 'true'}
Format did not work for me, since no radio button is selected after the format function was called.
Anyway, thanks for your help

**Comment by johhansantana** [comment]
I tried your fix @d-winter it works at the end I get the values as booleans but the radio buttons do not get highlighted.

```jsx
<label>
  <Field
    name="provideTransportation"
    component="input"
    type="radio"
    value="true"
    parse={val => val === "true"}
  />{" "}
  Yes
</label>
<label>
  <Field
    name="provideTransportation"
    component="input"
    type="radio"
    value="false"
    parse={val => val === "true"}
  />{" "}
  No
</label>
```

**Comment by superKalo** [comment]
@johhansantana here's what worked for me:

```
<label>
  <Field
    /* ... */
    value={true}
    parse={val => val === "true"}
  />{" "}
  Yes
</label>
<label>
  <Field
    /* ... */
    value={false}
    parse={val => val === "true"}
  />{" "}
  No
</label>
```

Values I get now are booleans + the radio buttons do not get highlighted too.

**Comment by andrew-aladev** [comment]
```
value={false}
normalize={value => value === 'true'}
```

and that's it.
