### ISSUE TITLE
Add support for Field-level validation

### ISSUE THREAD

**Issue by stalmok** [erikras/redux-form-material-ui#76]
It was added to redux-form v6.3.0: https://github.com/erikras/redux-form/releases/tag/v6.3.0

**Comment by jrocketfingers** [comment]
I've tried the field level validation, and it works out of the box. The only issue is that the validate prop gets propagated down to the material-ui component.

Hopefully I'm gonna have time to get a PR out.

I'm probably gonna make sure that it gets eaten in `mapError`. Not sure if it's the best way to go though, and it's gonna warn that the variable is unused.

**Comment by erikras** [comment]
Published fix in `redux-form` [`v6.4.3`](https://github.com/erikras/redux-form/releases/tag/v6.4.3).

#78
