### ISSUE TITLE
Invalid prop `value` of type `string` supplied to `DatePicker`, expected `object`

### ISSUE THREAD

**Issue by jasan-s** [erikras/redux-form-material-ui#77]
I keep getting this error, on my date picker and timePicker. here is my code:

```
      <Field className = {`${flexItem} ${dayField}`} name= 'eventStartDay' component={DatePicker}
      defaultValue={null}
      hintText='Day' minDate = {tomorrow}/>
```

**Comment by Lube** [comment]
Default value on fields of reduxform is empty string

**Comment by erikras** [comment]
You need to pass `format={null}`. https://github.com/erikras/redux-form-material-ui/issues/37

http://stackoverflow.com/questions/40492077/setting-a-defaultvalue-for-timepicker-using-redux-form-and-materialui

**Comment by dchambers** [comment]
Thanks @erikras! I should have Googled this problem sooner as I wasted lots of time debugging something that's already been solved 😄 .

To prevent other people from tripping up on the same issue, might it be sensible for this to be the default value, or does that not really make sense?

Thanks for the awesome library!
