### ISSUE TITLE
Console Warning: Unknown prop `validate` on <input> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by mohamed-nazim** [erikras/redux-form-material-ui#78]
I get the following in console when I add 'validate' property to a field.

Warning: Unknown prop `validate` on <input> tag. Remove this prop from the element. 

What is the proper way of using this property?

**Comment by speedDeveloper** [comment]
I get the same error, even the example has the same error.
https://github.com/erikras/redux-form/issues/1249 mentions the problem. But I also don't understand how to implement it properly.

**Comment by erikras** [comment]
This was a bug. It will be fixed in the next RF release. https://github.com/erikras/redux-form/pull/2361

**Comment by speedDeveloper** [comment]
Thank you very much Erik!

**Comment by itditp** [comment]
waitWait) Thank you, Erik!

**Comment by erikras** [comment]
Published fix in `redux-form` [`v6.4.3`](https://github.com/erikras/redux-form/releases/tag/v6.4.3).
