### ISSUE TITLE
Feature suggestion: setting 'active' prop causes field to gain focus

### ISSUE THREAD

**Issue by jcheroske** [erikras/redux-form-material-ui#8]
I'm curious about the possibility of having the `active` prop cause the underlying material-ui component to gain focus. It seems that, when a component gains focus, it calls an `onFocus` callback that's been handed to it by redux-form. This callback fires a `FOCUS` action, which results in a state mutation and the `active` flag being set on the ui component. Could the setting of the active field state, via the reducer plugin, do the reverse and cause the field's `focus()` method to be called? Right now, messing with the state directly does cause the `active` prop to be properly set on the ui component. But the component does not translate that into a call to its `focus()` method, afaik. These wrappers could see the change to the `active` prop and pass that down to the material ui component via a ref call. https://github.com/callemall/material-ui/issues/1594 demonstrates how to set focus on a mui field programmatically.

**Comment by erikras** [comment]
Seems potentially possible, yes.

**Comment by erikras** [comment]
I tried this, and it doesn't work. I'm calling `this.refs.component.focus()` whenever the `props.meta.active` changes from false to true, and it doesn't actually do anything. Bummer... 😢
