### ISSUE TITLE
Can't set a default value for SelectField

### ISSUE THREAD

**Issue by kvoth3** [erikras/redux-form-material-ui#81]
As the title says, I'm trying to set an initial value for my select field component and it does not show up as selected when rendered.

If working, example should be added to the live demo.

**Comment by Lube** [comment]
Having the same problem as we speak going to try to dig into it.

**Comment by Lube** [comment]
Ok found my issue I was passing immutable values to menuitems and my model had an inmutable value too so they are never the same.

Still don't know which is the clearest way to resolve this, probably something like having a function or prop to determine equality is the cleanest but it involves material-ui

**Comment by Lube** [comment]
Quick hack using ramda, you probably want to wrap select field to avoid boilerplate

```javascript
    <Field
      name='foo'
      component={SelectField}
      hintText='Select Foo'
      floatingLabelText='Foo'
      format={value => findIndex(propEq('id', value.id))(fooList)}
      normalize={value => fooList[value]}
      fullWidth
    >
      {fooList.map((fooElement, i) => (
        <MenuItem
          value={i}
          primaryText={fooElement.name}
        />
      ))}
    </Field>
```

**Comment by mihirsoni** [comment]
This library doesn't allow defaultValues.

You can read more about this [here](https://github.com/erikras/redux-form-material-ui#no-default-values)
