### ISSUE TITLE
RadioButtonGroup defaultSelected

### ISSUE THREAD

**Issue by alexbahl** [erikras/redux-form-material-ui#84]
passing defaultSelected to the Field component that is using RadioButtonGroup as its component does not work making the default way to set a a default value not work.

**Comment by xuewenfei** [comment]
you can do like this:
<Field style={{width: "100%"}}  input={{value: "xx"}} name="name" component={RadioButtonGroup}>

this value will pass to defaultSelected of RadioButtonGroup

**Comment by xuewenfei** [comment]
sorry, this does not work, I create a fork for this bug

**Comment by xuewenfei** [comment]
please use initialValues in container , don't set defaultSelected manually.

example：
let stateValues;
function mapStateToProps(state, ownProps) {
  stateValues = state;
  const result = {
    initialValues: {
      grade_part: ownProps.profile.gradePart,
      subject: ownProps.profile.subject,
    }
  };
  return result;
}

SubjectForm = reduxForm({
  form: 'subject'
})(SubjectForm);

SubjectForm =connect(mapStateToProps)(SubjectForm);

export default SubjectForm;

**Comment by erikras** [comment]
Fix published in [`v4.1.3`](https://github.com/erikras/redux-form-material-ui/releases/tag/v4.1.3).
