### ISSUE TITLE
Hiding redux form field component

### ISSUE THREAD

**Issue by Morkowski** [erikras/redux-form-material-ui#85]
Why can't we hide implementation details from redux form and use those components like material-ui. 
For example:

```
import { Checkbox } from 'redux-form-material-ui';
<Checkbox name="agreeToTerms" label="Agree to terms?" />
```

instead of:

`<Field name="agreeToTerms" component={Checkbox} label="Agree to terms?"/>`
?

**Comment by mihirsoni** [comment]
That is by design , and it makes it consistent with ```redux-form``` It just takes care for view part of it.
