### ISSUE TITLE
Set initial value on AutoComplete with DataSource

### ISSUE THREAD

**Issue by dcarneiro** [erikras/redux-form-material-ui#86]
I'm trying to set the initial value on an AutoComplete field with a DataSource. Sadly I'm probably doing something wrong.

I have the following dataSource

```javascript
export const countryCodes = [
  { text: 'Afghanistan', value: 'af' },
  { text: 'Åland Islands', value: 'ax' },
  { text: 'Albania', value: 'al' },
  ...
```

And the component

```javascript
import { AutoComplete as MUIAutoComplete } from 'material-ui';

render() {
    ...
    const dataSourceConfig = { text: 'text', value: 'value' };

    ...
    return (
      ..
      <Field
        name="isoCountryCode"
        component={AutoComplete}
        filter={MUIAutoComplete.caseInsensitiveFilter}
        dataSource={countryCodes}
        dataSourceConfig={dataSourceConfig} 
      />
      ...
   )
```

But I'm unable to set the form initial value. I'm not sure if I should pass the full item, just the text or the value, but neither of them seem to work. The following code correctly sets the user name, but the `AutoComplete` is empty:

```javascript
export default connect(
  (state) => ({
    initialValues: {
      name: 'Jane Doe',
      isoCountryCode: countryCodes[1],
    }
  }),
)(decoratedForm(UserForm));
```

**Comment by braxtonchristensen** [comment]
did you figure this out? i'm facing the same issue.

**Comment by DanilloCorvalan** [comment]
Same problem here, seems they do not accept objects and the datasourceconfig.

**Comment by yellowspaceboots** [comment]
Hey guys! I am running into the same issue. Initial values works as expected on the text input fields but not on autocomplete. Has anyone been able to get this working? Thanks!

**Comment by hluedeke** [comment]
I'm in this boat. I'm also noticing that if the AutoComplete is re-mounted (eg. in StepperContent) that the search text is not preserved (the value does, however, remain in the redux-form state)

**Comment by pablocordoba11** [comment]
I Have the same problem, Anyone can solve out that?

**Comment by sebastienfi** [comment]
https://github.com/erikras/redux-form-material-ui/pull/140

**Comment by fallanic** [comment]
It works for me when passing a hash as the initial value 

```
import AutoComplete from 'material-ui/AutoComplete';
import {
	AutoComplete as RFMaterialAutoComplete
} from 'redux-form-material-ui';

<Field
	name="myAutocompleteField"
	component={RFMaterialAutoComplete}
	type="text"
	filter={AutoComplete.fuzzyFilter}
	hintText="Select a value"
	dataSource={anArrayOfValueAndTextHashes}
	dataSourceConfig={{ value: 'value', text: 'text' }}
	openOnFocus
/>
```

initialValues

```
{
  initialValues: {
    myAutocompleteField: {
      text: 'something',
      value: 12345
    }
  }
}
```


Hope that helps.

**Comment by fallanic** [comment]
It looks like the latest code on `master` fixes that issue too, unfortunately no new version has been published.

Meanwhile I forked the repo, and committed my build, and it seems to work fine.

In my `package.json` I just replaced 
```
"redux-form-material-ui": "^4.2.0",
```
by
```
"redux-form-material-ui": "https://github.com/fallanic/redux-form-material-ui/tarball/a0d8c679eacf889ffb88a684db31b2e321bb4f11",
```

It's not great, but it will do the job until the next version published on npm.

**Comment by ddawkins7** [comment]
When will there be a release with this fix ?

**Comment by mihirsoni** [comment]
This has been fixed with latest version of 4.x
