### ISSUE TITLE
Export helper functions

### ISSUE THREAD

**Issue by Guibod** [erikras/redux-form-material-ui#89]
I'd like to wrap my own custom fields that have the same behavior as MUI component. Unfortunately neither `createComponent` or `mapError` functions are exported in the module.

Could it be possible to do so, that would spare me duplicate code. :)

**Comment by mihirsoni** [comment]
Hi @Guibod  

I would suggest if you could create PR for new component. It wouldn't be good idea to export private API. 

Feel free to open PR for new Component. I am closing this for now and feel free to have discussion on this.
