### ISSUE TITLE
New props.input needed by Redux Form and React 15.2

### ISSUE THREAD

**Issue by timothyallan** [erikras/redux-form-material-ui#9]
With the new breaking change in RF RC2, the ```createComponent``` function in RFMUI doesn't work. I can get it going by changing ```render``` to use ```mapProps(this.props.input)```, but that's going to break all other versions of Redux Form. 

I'd submit a PR, but I'm not sure how you want to handle previous versions?

**Comment by estaub** [comment]
Timothy, sorry to hijack a bit, but could you link to whatever describes the breaking change?  I can't find it.

**Comment by timothyallan** [comment]
Yep sure @estaub https://github.com/erikras/redux-form/releases/tag/v6.0.0-rc.2

**Comment by erikras** [comment]
Just fixed this in [`v3.0.0`](https://github.com/erikras/redux-form-material-ui/releases/tag/v3.0.0).
