### ISSUE TITLE
Access value of fields

### ISSUE THREAD

**Issue by jduncanRadBlue** [erikras/redux-form-material-ui#91]
Forgive me if this is a novice question!  I'm new to react and material-ui.  I'm trying to access the values that a user inputs into TextFields for logging in.  At this point all I am trying to do is spit out the values on to the console that the user entered into username and password within a form.  
I am getting this error:  
Uncaught TypeError: Cannot read property 'userName' of undefined
    at Object._handleSubmit [as onTouchTap]

Any ideas as to why userName is undefined? 

Here's the code:
[Login.txt](https://github.com/erikras/redux-form-material-ui/files/745341/Login.txt)

**Comment by mihirsoni** [comment]
You can try code from example repo and try. Sorry for the late reply.
