### ISSUE TITLE
RadField value is convert to string in store

### ISSUE THREAD

**Issue by BrunoQuaresma** [erikras/redux-form-material-ui#93]
I have.:

```
<Field
    label="Android"
    value={1}
    name="operational_system_id"
    type="radio"
    component={Radio}
    format={null}
  />
```

Radio is:

```
import { Radio as SnRadio } from 'supernova-inloco'

const Radio = ({ input, label }) => {
  return (
    <SnRadio
      {...input}
      label={label}
    />
  )
}

export default Radio
```

This cause a problem that when I click in the radio option it always come with checked equal to false because the value in radio is 1(number) and in the store is "1" (string).

**Comment by waclock** [comment]
I had a similar issue. You should use as value a string, in this case you could do this:

`<Field
    label="Android"
    value="1" // or `${1}`
    name="operational_system_id"
    type="radio"
    component={Radio}
    format={null}
  />`
