### ISSUE TITLE
[SelectField] Clicking on the arrow empties the field value

### ISSUE THREAD

**Issue by adamtal3** [erikras/redux-form-material-ui#94]
```
redux: 3.6.0
react:  15.4.0
redux-form: 6.4.3
redux-form-material-ui: 4.1.2
```

It seems that clicking on the small arrow triggers a blur event with an empty value which updates the form state.

This fixes the issue for me (simplified):
`
<Field component={SelectField} {...fieldProps} onBlur={(e) => ({e.preventDefault()})}>
`

**Comment by mihirsoni** [comment]
This should be fixed in #95
